-   id: validate_manifest
    name: Validate Pre-Commit Manifest
    description: This validator validates a pre-commit hooks manifest file
    entry: pre-commit-validate-manifest
    language: python
    files: ^(\.pre-commit-hooks\.yaml|hooks\.yaml)$
#-   id: ansible-lint
#    name: Ansible-lint
#    description: This hook runs ansible-lint.
#    entry: ansible-lint
#    language: python
#    files: \.(yaml|yml)$
