---
default_language_version:
    python: python3.6

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
        args: ['--maxkb=123']
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
        exclude: >
                  (?x)^(
                      clean.bat|
                      build.bat|
                      mvnw.cmd|
                      .mvn/
                  )$
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
    -   id: check-symlinks
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: detect-private-key
        exclude: >
                  (?x)^(
                      .ssh/id_rsa|
                      roles/jenkins-master/defaults/main.yml|
                      roles/jenkins-master/README.md
                  )$
    -   id: double-quote-string-fixer
    -   id: name-tests-test
        exclude: >
                  (?x)^(
                      .*/molecule/default/tests/test_default.py
                  )$
    -   id: no-commit-to-branch
        args: [--branch, develop, --branch, master, --branch, release/*]
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: requirements-txt-fixer
    -   id: sort-simple-yaml
    -   id: flake8
        args: [--max-line-length=120]
    -   id: file-contents-sorter
-   repo: https://github.com/pre-commit/pre-commit.git
    rev: v1.16.1
    hooks:
    -   id: validate_manifest
-   repo: https://github.com/asottile/reorder_python_imports.git
    rev: v1.4.0
    hooks:
    -   id: reorder-python-imports
#        language_version: python2.7
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v1.0.0
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/willthames/ansible-lint.git
    rev: v4.1.0
    hooks:
    -   id: ansible-lint
        files: \.(yaml|yml)$
        exclude: '.travis.yml'
-   repo: git://github.com/doublify/pre-commit-hindent
    sha: master
    hooks:
    -   id: hindent
-   repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
    -   id: shell-lint
        #entry: pre_commit_hooks/shell-lint.sh -x
        args: [-x]
        exclude: >
                  (?x)^(
                      mvnw|
                      hooks
                  )$
#-   repo: git://github.com/doublify/pre-commit-clang-format
#    sha: 994f99b6498e9c76341367ecaf76c69dfb4ea4f2
#    hooks:
#    -   id: clang-format
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.17.1
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
    -   id: autopep8
#-   repo: https://github.com/PyCQA/bandit
#    rev: master
#    hooks:
#    - id: bandit
-   repo: https://github.com/IamTheFij/ansible-pre-commit
    rev: v0.1.2
    hooks:
    -   id: encryption-check
