---
language: python
python: "2.7"
env:
  - ANSIBLE_VERSION=1.9.2
cache: bundler
#sudo: false
sudo: required
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install curl
 - sudo apt-get install -qq python-apt python-pycurl

install:
  # Install Ansible.
#  - pip install ansible>=1.6.0
  # Install Ansible.
  - sudo pip install ansible==$ANSIBLE_VERSION

  # Add ansible.cfg to pick up roles path.
  #- "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

# Install required dependencies.
#  - git clone https://github.com/AlbanAndrieu/ansible-supervisor_task.git supervisor
#  - ansible-galaxy install alban.andrieu.webmin
#  - ansible-galaxy install alban.andrieu.xvbf
#  - ansible-galaxy install alban.andrieu.zfs
#  - ansible-galaxy install alban.andrieu.dropbox
#  - ansible-galaxy install alban.andrieu.selenium
#  - ansible-galaxy install alban.andrieu.conky
#  - ansible-galaxy install alban.andrieu.subversion
#  - ansible-galaxy install alban.andrieu.css
#  - ansible-galaxy install alban.andrieu.security
#  - ansible-galaxy install alban.andrieu.zap
#  - ansible-galaxy install alban.andrieu.cmake
#  - ansible-galaxy install alban.andrieu.shell
#  - ansible-galaxy install alban.andrieu.eclipse
#  - ansible-galaxy install alban.andrieu.jboss
#  - ansible-galaxy install alban.andrieu.windows
#  - ansible-galaxy install alban.andrieu.cpp
#  - ansible-galaxy install alban.andrieu.pagespeed
#  - ansible-galaxy install alban.andrieu.jmeter
#  - ansible-galaxy install alban.andrieu.mon
#  - ansible-galaxy install alban.andrieu.grive
#  - ansible-galaxy install alban.andrieu.web
#  - ansible-galaxy install alban.andrieu.common
#  - ansible-galaxy install alban.andrieu.administration
#  - ansible-galaxy install alban.andrieu.workstation
#  - ansible-galaxy install alban.andrieu.dns
#  - ansible-galaxy install alban.andrieu.tomcat
#  - ansible-galaxy install alban.andrieu.synergy

  # Update Ansible submodule.
  - git pull && git submodule ini
  #- git submodule update && git submodule status
  - git submodule foreach git checkout master
script:
  # Check ansible version
  - ansible --version
  - export ANSIBLE_ROLES_PATH="../"

  # Prepare tests
#  - echo localhost > inventory

  # Check syntax
  # Check the role/playbook's syntax.
  - ansible-playbook --syntax-check -i hosts nabla.yml --connection=local

  # First run
  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i hosts nabla.yml --connection=local --sudo

  # Second run Idempotence test
  # Run the role/playbook again, checking to make sure it's idempotent.
#  - >
#    ansible-playbook -i hosts workstation.yml --connection=local --sudo
#    | grep -q 'changed=0.*failed=0'
#    && (echo 'Idempotence test: pass' && exit 0)
#    || (echo 'Idempotence test: fail' && exit 1)

  - sudo /etc/init.d/jenkins status || exit 1
  - sudo /etc/init.d/nexus status || exit 1
  - sudo /etc/init.d/mon status || exit 1

  # Test whether kibana is running correctly.
  - curl http://localhost/
