#sudo ansible-playbook -i hosts-albandri -c local -v certificate.yml -vvvv --ask-sudo-pass | tee setup.log

- hosts: all
  gather_facts: true
  tasks:
    - name: group hosts by distribution
      group_by: key="{{ ansible_distribution }}-{{ ansible_distribution_version }}"

- name: Apply ssl configuration to all nodes
#  hosts: Ubuntu-12*:Ubuntu-14*
  hosts: workstation
  gather_facts: false
#  remote_user: root
  roles:
    - role: ssl.certificate
      ssl_certs_country: "FR"
      ssl_certs_locality: "Paris"
      ssl_certs_organization: "Nabla"
      ssl_certs_state: "Ile de France"
      #ssl_certs_common_name: "{{ansible_fqdn}}"
      ssl_certs_common_name: "nabla.freeboxos.fr"
      ssl_certs_days: "365"
      #ssl_certs_fields: "/C={{ssl_certs_country}}/ST={{ssl_certs_state}}/L={{ssl_certs_locality}}/O={{ssl_certs_organization}}/CN={{ssl_certs_common_name}}"
      ssl_certs_path_owner: "root"
      #ssl_certs_path_group: "root"
      ssl_certs_mode: 700

- name: Install java certificate
  connection: local
  hosts: workstation
#  remote_user: root
#  accelerate: true

  roles:
#    - role: java.certificate
#      java_certificate_host: mail.google.com
#      java_certificate_port: 443

#    - role: java.certificate
#      java_certificate_host: nbala.freeboxos.fr
#      java_certificate_port: 443
#
#    - role: java.certificate
#      java_certificate_host: home.nabla.mobi
#      java_certificate_port: 443

#sonar
#    - role: java.certificate
#      java_certificate_host: home.nabla.mobi
#      java_certificate_port: 8999

    - role: java.certificate
      java_certificate_host: travis-ci.org
      java_certificate_port: 443

    - role: java.certificate
      java_certificate_host: github.com
      java_certificate_port: 443
