#see https://blog.trifork.com/2013/04/02/ansible-example-playbook-to-setup-jenkins-slave/

#for testing purpose
#sudo ansible-playbook -i hosts -c local -v jenkins-slave.yml -vvvv

#as root 
#ansible-playbook jenkins-slave.yml -i hosts -vvvv
#as albandri 
#ansible-playbook jenkins-slave.yml -i hosts -vvvv --ask-sudo-pass --sudo
# --extra-vars "jenkins_username=aandrieu jenkins_password=tbd"

- name: Apply hostname configuration
#  hosts: test-boxes
  hosts: all  
  user: root
#  connection: local  
    
  roles:
    - hostname

- name: Apply common configuration to all jenkins slaves
#  hosts: test-boxes
  hosts: jenkins-slaves
#  sudo: yes
#  user: vagrant
  remote_user: root  
  connection: local    
#  remote_user: vagrant

  vars_files:
  - [ "roles/alban.andrieu.jenkins-slave/defaults/main.yml" ]
  - [ "roles/alban.andrieu.jenkins-slave/vars/{{ ansible_distribution }}-{{ ansible_architecture }}.yml", "roles/alban.andrieu.jenkins-slave/vars/{{ ansible_distribution }}.yml" ]

  roles:
    - { role: alban.andrieu.jenkins-slave,
        docker_files_enable: yes,
        docker_files_generated_directory: "roles/alban.andrieu.jenkins-slave"
        #user: "albandri",
        #home: "/workspace/users/albandri10"     
      }    

  vars:    
    jenkins_jdk7_enable: no
#    jenkins_home_dir: "/jenkins"
#    jenkins_slave_home: "/kgr-mvn"

#- name: Apply swarm configuration to all jenkins slaves
#  hosts: test-boxes
#  sudo: yes
#  user: vagrant
#  connection: local    
##  remote_user: vagrant
#
#  vars_prompt:
#  - name: jenkins_username
#    prompt: "What is your jenkins user?"
#    private: no
#  - name: jenkins_password
#    prompt: "What is your jenkins password?"
#    private: yes
#
#  roles:
#    - alban.andrieu.jenkins-swarm
#
#  vars:    
#    jenkins_home: "/jenkins"
    
# This playbook can be run using vagrant (on virtual box). 
- name: Install xvbf
#  hosts: test-boxes
  hosts: xvbf 
  user: root
#  connection: local
  
  roles:
    - alban.andrieu.xvbf

