#for testing purpose
#sudo ansible-playbook -i hosts -c local -v jenkins-master.yml -vvvv

#as root 
#ansible-playbook jenkins-master.yml -i hosts -vvvv
#as albandri 
#ansible-playbook jenkins-master.yml -i hosts -vvvv --ask-sudo-pass --sudo
# --extra-vars "jenkins_username=aandrieu jenkins_password=tbd"

- name: Apply configuration to jenkins master
  hosts: jenkins-master
  remote_user: root
#  connection: local

  roles:
    - { role: jenkins-master,
        docker_files_enable: yes,
        docker_files_generated_directory: "roles/jenkins-master",
        #user: "albandri",
        #home: "/workspace/users/albandri10",      
      }
      
  vars:
      jenkins_proxy: apache
      jenkins_proxy_hostname: localhost
#      jenkins_ssh_key_file: "{{resources_to}}/resources/jenkins/ssh_key"    # (you can manage remote files with Stouts.resources role)
      jenkins_ssh_key_file: "~/.ssh/id_rsa.pub"
      jenkins_http_port: 8380
      jenkins_proxy_port: 7070                     
#      jenkins_home_dir: /jenkins
      jenkins_java_args:
        - "-Xmx1024m"
        - "-XX:MaxPermSize=512m"
        - "-Djava.awt.headless=true"
      jenkins_prefix: "/jenkins"
      jenkins_plugins:
        - "ws-cleanup"
        - "envinject"
        - "artifactdeployer"
        - "nodenamecolumn"
        - "summary_report"
        - "publish-over-cifs"
        - "progress-bar-column-plugin"
        - "thinBackup"
        - "token-macro"
        - "jobConfigHistory"
        - "scons"
        - "downstream-buildview"
        - "scm-sync-configuration"
        - "deploy"
        - "docker-plugin"
        - "build-publisher"
        - "sonar"
        - "xvfb"
        - "windows-slaves"
        - "m2release"
        - "git"
        - "scm-api"
        - "maven-repo-cleaner"
        - "ssh-agent"
        - "clover"
        - "environment-script"
        - "stepcounter"
        - "plugin-usage-plugin"
        - "jenkins-cloudformation-plugin"
        - "cvs"
        - "jira"
        - "JiraTestResultReporter"
        - "checkmarx"
        - "selenium"
        - "sonatype-ci"
        - "jobtype-column"
        - "findbugs"
        - "batch-task"
        - "warnings"
        - "violation-columns"
        - "configurationslicing"
        - "parameterized-trigger"
        - "sounds"
        - "job-exporter"
        - "preSCMbuildstep"
        - "fitnesse"
        - "dashboard-view"
        - "gearman-plugin"
        - "jquery-ui"
        - "gatling"
        - "job-node-stalker"
        - "favorite"
        - "build-pipeline-plugin"
        - "postbuild-task"
        - "skip-certificate-check"
        - "maven-info"
        - "crowd2"
        - "disk-usage"
        - "node-iterator-api"
        - "ssh"
        - "stashNotifier"
        - "publish-over-ssh"
        - "sitemonitor"
        - "build-metrics"
        - "promoted-builds"
        - "flexible-publish"
        - "selenium-builder"
        - "tasks"
        - "computer-queue-plugin"
        - "saferestart"
        - "throttle-concurrents"
        - "ant"
        - "countjobs-viewstabbar"
        - "email-ext"
        - "credentials"
        - "cobertura"
        - "nodejs"
        - "audit-trail"
        - "svnpublisher"
        - "text-finder-run-condition"
        - "versioncolumn"
        - "global-build-stats"
        - "plot"
        - "jquery"
        - "svn-tag"
        - "show-build-parameters"
        - "conditional-buildstep"
        - "copy-to-slave"
        - "maven-plugin"
        - "view-job-filters"
        - "jshint-checkstyle"
        - "rebuild"
        - "matrix-project"
        - "performance"
        - "copyartifact"
        - "speaks"
        - "groovy"
        - "svn-revert-plugin"
        - "ldap"
        - "claim"
        - "docker-build-step"
        - "hudson-jirareporter-plugin"
        - "nodelabelparameter"
        - "ansicolor"
        - "translation"
        - "sidebar-link"
        - "bulk-builder"
        - "jenkins-jira-issue-updater"
        - "checkstyle"
        - "mttr"
        - "ssh-slaves"
        - "swarm"
        - "ssh-credentials"
        - "subversion"
        - "antisamy-markup-formatter"
        - "covcomplplot"
        - "trac"
        - "testng-plugin"
        - "greenballs"
        - "test-stability"
        - "external-monitor-job"
        - "docker-build-publish"
        - "any-buildstep"
        - "project-stats-plugin"
        - "timestamper"
        - "build-name-setter"
        - "build-timeout"
        - "prereq-buildstep"
        - "caliper-ci"
        - "pmd"
        - "lastsuccessversioncolumn"
        - "ec2"
        - "dry"
        - "analysis-collector"
        - "analysis-core"
        - "insight-ci"
        - "description-setter"
        - "publish-over-ftp"
        - "groovy-postbuild"
        - "hudson-apiv2-plugin"
        - "build-environment"
        - "seleniumrc-plugin"
        - "git-client"
        - "monitoring"
        - "text-finder"
        - "ftppublisher"
        - "built-on-column"
        - "run-condition"
        - "lastfailureversioncolumn"
        - "mask-passwords"
        - "hp-application-automation-tools-plugin"
        - "project-description-setter"
        - "build-with-parameters"
        - "svnmerge"
        - "git-parameter"
        - "javadoc"
        - "build-failure-analyzer"
        - "confluence-publisher"
        - "html5-notifier-plugin"
        - "violations"
        - "next-executions"
        - "matrix-auth"
        - "testInProgress"
        - "copy-data-to-workspace-plugin"
        - "mailer"
        - "next-build-number"
        - "qc"
        - "multiple-scms"
        - "job-import-plugin"
        - "files-found-trigger"
        - "compact-columns"
        - "build-keeper-plugin"
        - "pam-auth"
        - "log-parser"
        - "locale"
        - "all-changes"
        - "dependencyanalyzer"
        - "WebSVN2"
        - "SquishPlugin"
        - "slave-status"
#      jenkins_jobs:
#        - name: test
#          action: delete
