#as root 
#ansible-playbook jenkins-slave-production -i hosts -vvvv
#as albandri 
#ansible-playbook jenkins-slave-production -i hosts -vvvv --ask-sudo-pass --sudo
# --extra-vars "jenkins_username=aandrieu jenkins_password=tbd"

- name: apply common configuration to all jenkins slaves
  hosts: jenkins-slaves
  remote_user: root
#  hosts: albandri  
#  connection: local  
#  hosts: test-boxes
#  sudo: yes
#  remote_user: vagrant
  vars_files:
  - [ "roles/jenkins-slave/defaults/main.yml" ]
  - [ "roles/jenkins-slave/vars/{{ ansible_distribution }}-{{ ansible_architecture }}.yml", "roles/jenkins-slave/vars/{{ ansible_distribution }}.yml" ]

#  vars_prompt:
#  - name: jenkins_username
#    prompt: "What is your jenkins user?"
#    private: no
#  - name: jenkins_password
#    prompt: "What is your jenkins password?"
#    private: yes

  roles:
    - jenkins-slave
