---
# from galaxy
# ansible-galaxy install -r requirements.yml -p ./roles/ --ignore-errors
# ansible-galaxy collection install -r requirements.yml

collections:
  #- name: community.crypto
  #- name: community.general
  - name: ansible.utils
  #- name: ansible.netcommon
  #- name: ansible.posix
  #- name: rtnp.galaxie_clans

roles:
  - src: https://github.com/AlbanAndrieu/ansible-administration.git
    name: albanandrieu.administration
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-awstats.git
    name: albanandrieu.awstats
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-cmake.git
    name: albanandrieu.cmake
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-common.git
    name: albanandrieu.ansible_common
    version: 'master'

  - src: https://github.com/AlbanAndrieu/ansible-conky.git
    name: albanandrieu.conky
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-cpp.git
    name: albanandrieu.ansible_cpp
    version: master

  - src: 'https://github.com/AlbanAndrieu/ansible-css'
    name: 'albanandrieu.css'
    scm: 'git'
    version: 'master'

  - src: https://github.com/AlbanAndrieu/ansible-dns.git
    name: albanandrieu.ansible_dns
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-dropbox.git
    name: albanandrieu.dropbox
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-eclipse.git
    name: albanandrieu.eclipse
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-evasive.git
    name: albanandrieu.evasive
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-gcc.git
    name: albanandrieu.gcc
    version: master

  #- src: 'https://github.com/AlbanAndrieu/ansible-grive'
  #  name: 'albanandrieu.grive'
  #  scm: 'git'
  #  version: 'master'

  #TODO
  #- src: https://github.com/Stouts/Stouts.hostname
  #  version: master
  #  name: Stouts.hostname

  - src: 'https://github.com/AlbanAndrieu/ansible-hostname'
    name: 'albanandrieu.ansible_hostname'
    scm: 'git'
    version: 'master'

  - src: 'https://github.com/AlbanAndrieu/ansible-jboss'
    name: 'albanandrieu.jboss'
    scm: 'git'
    version: 'master'

  - src: https://github.com/AlbanAndrieu/ansible-jdiskreport.git
    name: albanandrieu.jdiskreport
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-jenkins-slave.git
    name: albanandrieu.jenkins_slave
    version: master

  - src: 'https://github.com/AlbanAndrieu/ansible-jenkins-swarm'
    name: 'albanandrieu.jenkins-swarm'
    scm: 'git'
    version: 'master'

  - src: 'https://github.com/AlbanAndrieu/ansible-jmeter'
    name: 'albanandrieu.jmeter'
    scm: 'git'
    version: 'master'

  #- src: 'https://github.com/AlbanAndrieu/ansible-logstash-settings'
  #  name: 'albanandrieu.logstash-settings'
  #  scm: 'git'
  #  version: 'master'

  - src: 'https://github.com/AlbanAndrieu/ansible-mon'
    name: 'albanandrieu.mon'
    scm: 'git'
    version: 'master'

  - src: 'https://github.com/AlbanAndrieu/ansible-owasp-wte'
    name: 'albanandrieu.owasp-wte'
    scm: 'git'
    version: 'master'

  - src: https://github.com/AlbanAndrieu/ansible-pagespeed.git
    name: albanandrieu.pagespeed
    version: master

  - src: 'https://github.com/AlbanAndrieu/ansible-phpvirtualbox'
    name: 'albanandrieu.phpvirtualbox'
    scm: 'git'
    version: 'master'

  - src: 'https://github.com/AlbanAndrieu/ansible-private-bower'
    name: 'albanandrieu.private-bower'
    scm: 'git'
    version: 'master'

  - src: https://github.com/AlbanAndrieu/ansible-scons.git
    name: albanandrieu.scons
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-selenium.git
    name: albanandrieu.selenium
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-shell.git
    name: albanandrieu.shell
    version: master

  - src: 'https://github.com/AlbanAndrieu/ansible-solaris'
    name: 'albanandrieu.solaris'
    scm: 'git'
    version: 'master'

  #- src: 'https://github.com/AlbanAndrieu/ansible-squirrel'
  #  name: 'albanandrieu.squirrel'
  #  scm: 'git'
  #  version: 'master'

  - src: 'https://github.com/AlbanAndrieu/ansible-sublimetext'
    name: 'albanandrieu.sublimetext'
    scm: 'git'
    version: 'master'

  - src: 'https://github.com/AlbanAndrieu/ansible-subversion'
    name: 'albanandrieu.subversion'
    scm: 'git'
    version: 'master'

  - src: 'https://github.com/AlbanAndrieu/ansible-synergy'
    name: 'albanandrieu.synergy'
    scm: 'git'
    version: 'master'

  - src: 'https://github.com/AlbanAndrieu/ansible-tomcat'
    name: 'albanandrieu.tomcat'
    scm: 'git'
    version: 'master'

  - src: https://github.com/AlbanAndrieu/ansible-visualvm.git
    name: albanandrieu.visualvm
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-web.git
    name: albanandrieu.web
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-webmin.git
    name: albanandrieu.webmin
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-windows.git
    name: albanandrieu.windows
    version: master

  - src: 'https://github.com/AlbanAndrieu/ansible-workstation'
    name: 'albanandrieu.workstation'
    scm: 'git'
    version: 'master'

  - src: 'https://github.com/AlbanAndrieu/ansible-xvbf'
    name: 'albanandrieu.xvbf'
    scm: 'git'
    version: 'master'

  - src: https://github.com/AlbanAndrieu/ansible-yourkit.git
    name: albanandrieu.yourkit
    version: master

  - src: 'https://github.com/AlbanAndrieu/ansible-zap'
    name: 'albanandrieu.zap'
    scm: 'git'
    version: 'master'

  - src: 'https://github.com/AlbanAndrieu/ansible-zfs'
    name: 'albanandrieu.zfs'
    scm: 'git'
    version: 'master'

  #- src: 'https://github.com/AlbanAndrieu/ansible-login'
  - src: https://github.com/weareinteractive/ansible-login.git
    name: ansible-login
    version: master

  - src: 'https://github.com/AlbanAndrieu/ansible-newrelic'
    name: 'newrelic'
    scm: 'git'
    version: 'master'

  - src: https://github.com/AlbanAndrieu/devbox.chrome.git
    name: chrome
    version: master

  - src: https://github.com/AlbanAndrieu/Stouts.collectd.git
    name: Stouts.collectd
    version: master

  #- src: 'https://github.com/AlbanAndrieu/ansible-darthwade-wordpress'
  #  name: 'darthwade-wordpress'
  #  scm: 'git'
  #  version: 'master'
  #
  #- src: 'https://github.com/AlbanAndrieu/ansible-darthwade-wordpress-apache'
  #  name: 'darthwade-wordpress-apache'
  #  scm: 'git'
  #  version: 'master'

  #TODO nor more maintained
  #- src: 'https://github.com/AlbanAndrieu/ansible-role-base'
  #  name: 'elao-base'
  #  scm: 'git'
  #  version: 'master'
  #
  #- src: 'https://github.com/AlbanAndrieu/ansible-role-ruby'
  #  name: 'elao-ruby'
  #  scm: 'git'
  #  version: 'master'
  #
  #- src: 'https://github.com/AlbanAndrieu/ansible-role-sass'
  #  name: 'elao-sass'
  #  scm: 'git'
  #  version: 'master'

  #- src: angstwad.docker_ubuntu
  #  version: v3.4.1
  #  name: angstwad.docker-ubuntu

  - src: 'https://github.com/geerlingguy/ansible-role-pip'
    name: 'geerlingguy.pip'
    scm: 'git'
    version: 'master'

  - src: 'https://github.com/geerlingguy/ansible-role-docker'
    name: 'geerlingguy.docker'
    scm: 'git'
    version: 'master'

  #- src: 'https://github.com/AlbanAndrieu/docker.ubuntu'
  #  name: 'docker'
  #  scm: 'git'
  #  version: 'master'

  - src: https://github.com/geerlingguy/ansible-role-apache.git
    name: geerlingguy.apache
    version: master

  # Below replaced by https://github.com/geerlingguy/ansible-role-apache.git
  #- src: 'https://github.com/AlbanAndrieu/ansible-role-apache'
  #  name: 'geerlingguy.apache'
  #  scm: 'git'
  #  version: 'master'

  #- src: 'https://github.com/AlbanAndrieu/ansible-role-elasticsearch'
  #  name: 'geerlingguy.elasticsearch'
  #  scm: 'git'
  #  version: 'master'
  #
  #- src: 'https://github.com/AlbanAndrieu/ansible-role-elasticsearch-curator'
  #  name: 'geerlingguy.elasticsearch-curator'
  #  scm: 'git'
  #  version: 'master'

  - src: 'https://github.com/AlbanAndrieu/ansible-role-firewall'
    name: 'geerlingguy.firewall'
    scm: 'git'
    version: 'master'

  - src: 'https://github.com/AlbanAndrieu/ansible-role-git'
    name: 'geerlingguy.git'
    scm: 'git'
    version: 'master'

  #- src: 'https://github.com/AlbanAndrieu/ansible-role-kibana'
  #  name: 'geerlingguy.kibana'
  #  scm: 'git'
  #  version: 'master'
  #
  #- src: 'https://github.com/AlbanAndrieu/ansible-role-logstash'
  #  name: 'geerlingguy.logstash'
  #  scm: 'git'
  #  version: 'master'

  - src: https://github.com/geerlingguy/ansible-role-mysql.git
    name: geerlingguy.mysql
    version: master

  #- src: 'https://github.com/geerlingguy/ansible-role-php-xdebug'
  #  name: 'geerlingguy.php-xdebugl'
  #  scm: 'git'
  #  version: 'master'

  - src: 'https://github.com/AlbanAndrieu/ansible-role-nginx'
    name: 'geerlingguy.nginx'
    scm: 'git'
    version: 'master'

  - src: 'https://github.com/AlbanAndrieu/ansible-role-ntp'
    name: 'geerlingguy.ntp'
    scm: 'git'
    version: 'master'

  #- src: 'https://github.com/AlbanAndrieu/ansible-role-php'
  #  name: 'geerlingguy.php'
  #  scm: 'git'
  #  version: 'master'

  - src: https://github.com/geerlingguy/ansible-role-php.git
    name: geerlingguy.php
    version: master

  #- src: 'https://github.com/geerlingguy/ansible-role-php-versions'
  #  name: 'geerlingguy.php-versions'
  #  scm: 'git'
  #  version: 'master'

  - src: https://github.com/geerlingguy/ansible-role-php-mysql.git
    name: geerlingguy.php-mysql
    version: master

  - src: https://github.com/geerlingguy/ansible-role-phpmyadmin.git
    name: geerlingguy.phpmyadmin
    version: master

  #- src: 'https://github.com/AlbanAndrieu/ansible-role-phpmyadmin'
  #  name: 'geerlingguy.phpmyadmin'
  #  scm: 'git'
  #  version: 'master'

  - src: 'https://github.com/AlbanAndrieu/ansible-role-redis'
    name: 'geerlingguy.redis'
    scm: 'git'
    version: 'master'

  - src: https://github.com/geerlingguy/ansible-role-repo-epel.git
    name: geerlingguy.repo-epel
    version: master

  - src: https://github.com/geerlingguy/ansible-role-repo-remi.git
    name: geerlingguy.repo-remi
    version: master

  - src: 'https://github.com/geerlingguy/ansible-role-samba'
    name: 'geerlingguy.samba'
    scm: 'git'
    version: 'master'

  #- src: 'https://github.com/AlbanAndrieu/ansible-role-java'
  #  name: 'geerlingguy.java'
  #  scm: 'git'
  #  version: 'master'

  #- src: 'https://github.com/AlbanAndrieu/oracle-java'
  #  name: 'java'
  #  scm: 'git'
  #  version: 'master'

  - src: 'https://github.com/ansiblebit/oracle-java'
    name: 'ansiblebit.oracle-java'
    scm: 'git'
    version: 'master'

  - src: 'https://github.com/AlbanAndrieu/ansible-java-certificate'
    name: 'java-certificate'
    scm: 'git'
    version: 'master'

  - src: https://github.com/AlbanAndrieu/Stouts.jenkins.git
    name: jenkins-master
    version: master

  - src: https://github.com/Oefenweb/ansible-locales.git
    name: locale
    version: master

  - src: 'https://github.com/AlbanAndrieu/ansible-role-maven'
    name: 'maven'
    scm: 'git'
    version: 'master'

  - src: 'https://github.com/AlbanAndrieu/ansible-role-maven-color'
    name: 'maven-color'
    scm: 'git'
    version: 'master'

  #- src: 'https://github.com/AlbanAndrieu/ansible-monit'
  #  name: 'monit'
  #  scm: 'git'
  #  version: 'master'

  - src: https://github.com/AlbanAndrieu/ansible-sonatype_nexus.git
    name: nexus
    version: master

  - src: 'https://github.com/AlbanAndrieu/ansible-role-nodejs'
    name: 'geerlingguy.nodejs'
    scm: 'git'
    version: 'master'

  - src: https://github.com/AlbanAndrieu/Stouts.python.git
    name: python
    version: develop

  #- src: 'https://github.com/AlbanAndrieu/ansible-role-security'
  #  name: 'security'
  #  version: master

  #- src: 'https://github.com/AlbanAndrieu/ansible-sonar'
  #  name: 'sonar'
  #  version: master

  - src: https://github.com/geerlingguy/ansible-role-sonar-runner.git
    name: geerlingguy.sonar-runner
    version: master

  - src: 'https://github.com/geerlingguy/ansible-role-filebeat'
    name: 'geerlingguy.filebeat'
    scm: 'git'
    version: 'master'

  - src: https://github.com/jdauphant/ansible-role-ssl-certs.git
    name: ssl-certificate
    version: master

  - src: https://github.com/andrewrothstein/ansible-trust-ca.git
    name: ssl-ca-certificate
    version: master

  - src: https://github.com/andrewrothstein/ansible-tls.git
    name: andrewrothstein.tls
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-supervisor_task.git
    name: ansible-supervisor
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-vagrant-role.git
    name: vagrant
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-galaxy.ubuntu.virtualbox.git
    name: albanandrieu.virtualbox
    version: master

  - src: https://github.com/dj-wasabi/ansible-zabbix-agent.git
    name: dj-wasabi.zabbix-agent
    version: master

  - src: 'https://github.com/LIP-Computing/ansible-role-nvidia'
    name: 'opencl'
    scm: 'git'
    version: 'master'

  - src: https://github.com/elliotweiser/ansible-osx-command-line-tools.git
    name: elliotweiser.osx-command-line-tools
    version: master

  - src: https://github.com/geerlingguy/ansible-role-homebrew.git
    name: geerlingguy.homebrew
    version: master

  - src: 'https://github.com/geerlingguy/ansible-role-dotfiles'
    name: 'geerlingguy.dotfiles'
    scm: 'git'
    version: 'master'

  - src: 'https://github.com/geerlingguy/ansible-role-mas'
    name: 'geerlingguy.mas'
    scm: 'git'
    version: 'master'

  #- src: https://github.com/geerlingguy/mac-dev-playbook.git
  #  name: mac-dev-playbook
  #  version: master

  - src: 'https://github.com/ocha/ansible-role-yarn'
    name: 'yarn'
    scm: 'git'
    version: 'master'

  - src: 'https://github.com/geerlingguy/ansible-role-nfs'
    name: 'geerlingguy.nfs'
    scm: 'git'
    version: 'master'

  - src: https://github.com/Oefenweb/ansible-swapfile.git
    version: master
    name: ansible-swapfile

  - src: 'https://github.com/geerlingguy/ansible-role-varnish'
    name: 'geerlingguy.packer'
    scm: 'git'
    version: 'master'

  - src: https://github.com/geerlingguy/ansible-role-kubernetes
    name: 'geerlingguy.kubernetes'
    scm: 'git'
    version: 'master'

  - src: https://github.com/andrewrothstein/ansible-unarchive-deps.git
    version: master
    name: andrewrothstein.unarchive-deps

  - src: https://github.com/andrewrothstein/ansible-kubernetes-helm.git
    version: master
    name: andrewrothstein.kubernetes-helm

  - src: 'https://github.com/andrewrothstein/ansible-kubectl'
    name: 'andrewrothstein.kubectl'
    scm: 'git'
    version: 'master'

  - src: https://github.com/geerlingguy/ansible-role-clamav.git
    name: geerlingguy.clamav
    version: master

  - src: 'https://github.com/geerlingguy/ansible-role-packer'
    name: 'geerlingguy.varnish'
    scm: 'git'
    version: 'master'

  - src: https://github.com/andrewrothstein/ansible-terraform.git
    name: andrewrothstein.terraform
    version: master

  - src: 'https://github.com/ANXS/perl'
    name: 'anxs.perl'
    scm: 'git'
    version: 'master'

  - src: 'https://github.com/jermon/ansible-role-cpan'
    name: 'jermon.ansible-role-cpan'
    scm: 'git'
    version: 'master'

  - src: 'https://github.com/AlbanAndrieu/stack-docker'
    name: 'elastic/stack-docker'
    scm: 'git'
    version: 'master'

  # TODO https://github.com/Stouts/Stouts.openvpn
