#sudo ansible-playbook -i hosts-albandri -c local -v windows.yml | tee setup.log

- name: Install Windows 
  hosts: windows 
  user: root
#  connection: local
  roles:
    - role: alban.andrieu.windows
