#sudo ansible-playbook -i hosts -c local -v zabbix-agent.yml | tee setup.log

- hosts: all
  gather_facts: true
  tasks:
    - name: group hosts by distribution
      group_by: key="{{ ansible_distribution }}-{{ ansible_distribution_version }}"

- hosts: RedHat-7*:RedHat-6*:CentOS-6*:Ubuntu-12.04:Ubuntu-14.04
  gather_facts: false
  tasks:
    - name: group hosts for supported distributions
      group_by: key="supported"

- hosts: "!supported"
  gather_facts: false
  tasks:
    - name: fail for unsupported distribution
      fail: msg="{{ ansible_distribution }} {{ ansible_distribution_version }}
                 is not a supported OS for a Tower installation.  Supported
                 OSes include Red Hat Enterprise Linux 6/7, CentOS 6, or
                 Ubuntu 12.04/14.04."

# This playbook can be run using vagrant (on virtual box). 
- name: Install zabbix-agent 
  hosts: zabbix-agent
  remote_user: root
#  connection: local
  
  roles:
    - role: zabbix-agent
      name: zabbix-agent  
      
  vars:
      zabbix_agent_major: '2'
      zabbix_agent_minor: '2'
      zabbix_agent_revision: '7'
      zabbix_agent_ubuntu: "1:{{zabbix_agent_version}}-1+trusty"
      #zabbix_agent_Server: 127.0.0.1
    
