#ansible-playbook -i hosts-albandri -v albandri.yml --limit albandri-laptop-work -c local --ask-sudo-pass -vvvv | tee setup.log
# -c local  --ask-pass --ask-sudo-pass --sudo
#ansible all -m setup -i hosts-albandri --limit albandri-laptop-work -vvvv

- name: Assert platform is supported
  hosts: all
  remote_user: albandri
  gather_facts: true

  tasks:
    - name: Assert platform is supported
      assert:
        that:
          - ansible_os_family in ['Debian', 'RedHat', 'Windows', 'Solaris']
          - ansible_architecture in ['x86_64']

#supported version
#Solaris
##  when: ((ansible_distribution == 'Solaris') and (ansible_distribution_version not in ['11.1']))
#  when: ansible_distribution_release is defined and ansible_distribution_release == 'Solaris 10 10/08 s10x_u6wos_07b X86'
#  when: ansible_distribution_release is defined and ansible_distribution_release == 'Oracle Solaris 10 9/10 s10x_u9wos_14a X86'
#  when: ansible_distribution_release is defined and ansible_distribution_release == 'Oracle Solaris 10 1/13 s10x_u11wos_24a X86'
#SPARC
#  when: ansible_distribution_release is defined and ansible_distribution_release == 'Solaris 10 10/08 s10s_u6wos_07b SPARC'
#  when: ansible_distribution_release is defined and ansible_distribution_release == 'Oracle Solaris 10 1/13 s10s_u11wos_24a SPARC'
#REDHAT
#  when: ansible_distribution == 'RedHat' and ansible_lsb.major_release|int >= 5
#  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == "5"
#  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == "6"
#  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == "7"
#CENTOS
#  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == "6"
#  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == "7"
#UBUNTU
#https://wiki.ubuntu.com/DevelopmentCodeNames
#  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "12.04"
#  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'precise'
#  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "14.04"
#  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
#  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "16.04"
#  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'
#SLES
#  when: ansible_distribution == 'SLES' and ansible_distribution_version == "12"
#Windows
#  when: ansible_os_family == 'Windows' and ansible_os_name == 'Microsoft Windows Server 2008 R2 Enterprise'
#  when: ansible_os_family == 'Windows' and ansible_os_name == 'Microsoft Windows Server 2012 R2 Standard'

- hosts: all
  gather_facts: true
  remote_user: albandri
  tasks:
    - name: group hosts by distribution
      group_by: key="{{ ansible_distribution }}-{{ ansible_distribution_version }}"

- hosts: RedHat-7*:RedHat-6*:CentOS-7*:CentOS-6*:Ubuntu-17.04:Ubuntu-16.04:Ubuntu-14.04:Ubuntu-12.04
  gather_facts: false
  remote_user: albandri
  tasks:
    - name: group hosts for supported distributions
      group_by: key="supported"

- hosts: "!supported"
  gather_facts: false
  remote_user: albandri
  tasks:
    - name: fail for unsupported distribution
      fail: msg="{{ ansible_distribution }} {{ ansible_distribution_version }}
                 is not a supported OS for a Nabla installation.  Supported
                 OSes include Red Hat Enterprise Linux 6/7, CentOS 6/7, or
                 Ubuntu 17.04/16.04/14.04/12.04."

#- hosts: localhost
#
#  pre_tasks:
#    - name: Install Ansible-Galaxy dependencies
#      shell: ansible-galaxy install -r requirements.yml -p ./roles/ --ignore-errors

- name: Add repo configuration to all nodes
  hosts: RedHat-7*:RedHat-6*:CentOS-7*:CentOS-6*
  gather_facts: false
  remote_user: albandri


  roles:
    - geerlingguy.repo-epel
    - geerlingguy.repo-remi

#- name: Apply hostname configuration
#  hosts: all
#  remote_user: albandri
#
#
#  roles:
#    - alban.andrieu.hostname
#
#  vars:
#       hostname_hostname_loopback: "{{ ansible_hostname }} nabla"
       
- name: Apply common configuration to all nodes
  hosts: Ubuntu-17*:Ubuntu-16*:Ubuntu-14*:Ubuntu-12*
  gather_facts: false
  remote_user: albandri


  roles:
    - alban.andrieu.common

  vars:
       apt_notification_email: "alban.andrieu@misys.com"
       apt_upgrade_system_enabled: no

- name: Apply dns configuration to all nodes
  hosts: Ubuntu-17*:Ubuntu-16*:Ubuntu-14*:Ubuntu-12*
  gather_facts: false
  remote_user: albandri


  roles:
    - alban.andrieu.dns

  vars:
#       defaultdomain: nabla.freeboxos.fr
#       defaultsearch: nabla.freeboxos.fr. freeboxos.fr. home.nabla.mobi. nabla.mobi.
       defaultdomain: misys.global.ad
       defaultsearch: misys.global.ad
       dns_nameservers:
         - "10.0.2.3" # work dns
         - "10.25.200.3" # work dns
         - "10.21.200.3" # work dns
         - "8.8.8.8" # google dns
         - "8.8.4.4" # google dns
         - "192.168.0.254" # freebox dns
         - "192.168.1.1" #debian
         - "192.168.1.2" #debian
#paris
#      nameserver1: 10.21.200.3
#      nameserver2: 10.25.200.3
#gdynia
#      nameserver1: 10.7.109.27
#      nameserver2: 10.7.111.244

- name: Apply python configuration to all nodes
  hosts: all
  gather_facts: false
  remote_user: albandri
  become: yes


  roles:
    - python

  vars:
    python_ppa: no
    python_versions: [2.7, 3.5]
    python_install: [pylint, pandas]
    python_virtualenvs:
      - path: /opt/test/env

#Below ntp role is included in administration role
- name: Apply ntp configuration to all nodes
  hosts: all
  gather_facts: false
  remote_user: albandri
  become: yes


  roles:
    - geerlingguy.ntp

  vars:
       ntp_timezone: Europe/Paris

#Use below only if you want your servers to be part of build farm
- name: Apply administration configuration to all nodes
  hosts: Ubuntu-17*:Ubuntu-16*:Ubuntu-14*:Ubuntu-12*
  gather_facts: false
  remote_user: albandri


  roles:
    - alban.andrieu.administration

#Below firewall role is included in administration role
#- name: Apply firewall configuration to all nodes
#  hosts: Ubuntu-17*:Ubuntu-16*:Ubuntu-14*:Ubuntu-12*
#  gather_facts: false
#  remote_user: albandri
#
#
#  roles:
#    - geerlingguy.firewall
#
#  vars:
#       firewall_allowed_tcp_ports:
###
#       - "21" #FTP
#       - "22" #SSH
#       - "25" #SMTP
#       - "80" #HTTP / Nginx
#       - "82" #Varnish or Google +
#       - "123" #DNS
#       - "443" #HTTPS
#       - "2222" #SSH alternate
#       - "3306" #Mysql
#       - "3689" #FireFly
#       - "4040" #Subsonic
#       - "4444" #Selenium
#       - "4445" #Lumbermill/Selenium TODO???????
#       - "4243" #Docker
#       - "4949" #Munin
#       - "5000" #xrdp / Openstack
#       - "5001" #xrdp
#       - "5050" #CouchPatato
#       - "5678" #Private bower
#       - "6000" #Logstash
#       - "6082" #Varnish admin
#       - "6379" #Redis
#       - "6789" #Private bower git cache
#       - "7000" #FreeNas
#       - "7070" #Apache
#       - "7071" #Apache redirect gearman
#       - "7072" #Apache redirect jenkins
#       - "7073" #Apache redirect nabla
#       - "7074" #Apache redirect visma
#       - "7075" #Apache redirect sample
#       - "7076" #Apache redirect kibana
#       - "7077" #Apache redirect ansible tower (WAS)
#       - "7078" #Apache redirect Wordpress
#       - "8021" #FTP FreeNas
#       - "8081" #Nexus
#       - "8084" #OwnCloud
#       - "8085" #Fitness
#       - "8060" #Atlassion Fisheye
#       - "8082" #Atlassian JIRA
#       - "8083" #SickBeard
#       - "8080" #HTTP alternate (often used with Tomcat)
#       - "8089" #Bower registry
#       - "8091" #Transmission
#       - "8095" #Atlassion Crowd
#       - "8180" #JBoss
#       - "8181" #HeadPhone/JBoss http debug port
#       - "8200" #MiniDLNA
#       - "8280" #Tomcat HTTP
#       - "8380" #Jenkins
#       - "8381" #jenkins FreeNas
#       - "8443" #Tomcat HTTPS TODO???????
#       - "8480" #NGinx
#       - "8787" #JBoss remote debug port
#       - "8983" #Tomcat HTTP TODO???????
#       - "9042" #Supervisor
#       - "9000" #SonarQube
#       - "9090" #SABznbd/Jetty
#       - "9091" #Transmission
#       - "9990" #Jboss console
#       - "9200" #Elasticsearch
#       - "10000" #Webmin
#       - "20000" #Usermin
#       - "24800" #Synergy
#       - "25826" #Collectd
#       - "32400" #Plex
#Do not enable
#       - "139" #Samba/NetBIOS
#       - "445" #Samba/NetBIOS
#       - "17500" #DropBox
#       firewall_allowed_udp_ports:
#Do not enable
#       - "137" #Samba/NetBIOS
#       - "138" #Samba/NetBIOS
#
#       firewall_additional_rules:
#        - "iptables -A INPUT -i wlan1 -p udp -m udp -s mafreebox.freebox.fr -j ACCEPT" #Freebox tv
#        - "iptables -A OUTPUT -o wlan1 -p tcp -m tcp --dport 554 -j ACCEPT" #Freebox tv

- name: Apply security configuration
  hosts: security
  remote_user: albandri
  become: yes


  roles:
    - security

  vars:
      sudoers_enabled: no
      restart_ssh_enabled: false
      security_ssh_password_authentication: "yes"
      security_ssh_permit_root_login: "yes"
      security_ssh_x11_forwarding: "yes"
      security_fail2ban_enabled: false
      security_autoupdate_enabled: false #make yum to get stuck later

#Below cmake role is included in cpp role
#- name: Install cmake
#  hosts: cmake
#  remote_user: albandri
#
#
#  roles:
#    - alban.andrieu.cmake

#Below scons role is included in cpp role
#- name: Install scons
#  hosts: scons
#  remote_user: albandri
#
#
#  roles:
#    - alban.andrieu.scons

- include: cpp.yml

- include: java.yml

- include: certificate.yml

#- name: Install virtualbox
#  hosts: virtualbox
#  remote_user: albandri
#
#
#  roles:
#    - virtualbox
#
#  vars:
#      virtualbox_package_name: virtualbox
#      virtualbox_dkms_enable: no

- include: vagrant.yml

#  vars:
#       vagrant_libvirt_enabled: false
#       vagrant_windows_enabled: false
##      vagrant_url: https://dl.bintray.com/mitchellh/vagrant/vagrant_1.6.3_x86_64.deb

- include: docker.yml

- name: Install locale
  hosts: locale
  remote_user: albandri

  roles:
    - locale

#- name: Install zabbix-agent
#  hosts: zabbix-agent
#  remote_user: albandri
#
#  become: yes
#
#  roles:
#    - zabbix-agent
#
#  vars:
#      zabbix_agent_major: '2'
#      zabbix_agent_minor: '2'
#      zabbix_agent_revision: '7'
#      zabbix_agent_ubuntu: "1:{{zabbix_agent_version}}-1+trusty"
#      #zabbix_agent_Server: 127.0.0.1

- name: Install xvbf
  hosts: xvbf
  remote_user: albandri


  roles:
    - alban.andrieu.xvbf

- name: Install selenium
  hosts: selenium
  remote_user: albandri


  roles:
     - alban.andrieu.selenium

#
#- name: Install zfs
#  hosts: zfs
#  remote_user: albandri
#
#
#  roles:
#    - alban.andrieu.zfs

#Below dropbox is included in workstation role
#- name: Install dropbox
#  hosts: workstation
#  remote_user: albandri
##  sudo: yes
##  sudo_user: "{{ user }}"
#
#
#  roles:
#    - dropbox
#
#  vars:
#       docker_files_enable: yes
#       docker_files_generated_directory: "../roles/alban.andrieu.dropbox"

- name: Install workstation add-on
  hosts: workstation
  remote_user: albandri


  roles:
    - alban.andrieu.workstation

  vars:
       dropbox_user_directory: "/workspace/Dropbox"
       dropbox_user_host: "2366450895"
       nodejs_enabled: false
       variety_owner: "{{ user }}"
       variety_group: "{{ group }}"
       dropbox_owner: "{{ user }}"
       dropbox_group: "{{ group }}"

#- name: Apply swarm configuration to all jenkins slaves
#  hosts: jenkins-swarm
#  remote_user: albandri
#
#
#  vars_prompt:
#  - name: jenkins_username
#    prompt: "What is your jenkins user?"
#    private: no
#  - name: jenkins_password
#    prompt: "What is your jenkins password?"
#    private: yes
#
#  roles:
#    - jenkins-swarm
#
#  vars:
#       docker_files_enable: yes,
#       docker_files_generated_directory: "../roles/alban.andrieu.jenkins-swarm",

- name: Install webmin
  hosts: webmin
  remote_user: albandri


  roles:
    - alban.andrieu.webmin

  vars:
      docker_files_enable: no
      docker_files_generated_directory: "../roles/alban.andrieu.webmin"

- include: nexus.yml

- include: tomcat.yml

# This playbook deploys a simple standalone JBoss server.

#- include: jboss.yml

## This playbook deploys a MySQL database.
#- name: Deploy MySQL and configure the databases
#  hosts: mysql-servers
#  remote_user: albandri
#
#
#  roles:
#    - geerlingguy.mysql
#
#  vars:
#       mysql_innodb_log_file_size: "5M"
#       mysql_root_username: root
#       mysql_root_password: microsoft
#
## This playbook deploys an Apache database.
#- name: Deploy Apache and configure the server
#  hosts: apache-servers
#  remote_user: albandri
#
#
#  roles:
#    - geerlingguy.apache
#
#  vars:
#       apache_listen_port: 7070
#
#- name: Add dependencies for Apache like PHP
#  hosts: apache-servers
#  remote_user: albandri
#
#
#  roles:
#    - geerlingguy.php
#    - geerlingguy.php-mysql
#
#  vars:
#       php_date_timezone: "Europe/Paris"
#
#- name: Add admin tool for Apache like PHPmyAdmin
#  hosts: apache-servers
#  remote_user: albandri
#
#
#  roles:
#    - geerlingguy.phpmyadmin
#
#  vars:
#       phpmyadmin_mysql_user: root
#       phpmyadmin_mysql_password: microsoft
#       phpmyadmin_mysql_port: 7070
#       apache_listen_port: 7070
#       php_date_timezone: "Europe/Paris"
#       mysql_innodb_log_file_size: "5M"
#       mysql_root_username: root
#       mysql_root_password: microsoft

#WARNING jenkins-master role has disabled a2dissite 000-default
- name: Configure and deploy the nabla php sample application code to apache
  hosts: nabla-servers
  remote_user: albandri


  roles:
    - alban.andrieu.web

  vars:
       apache_listen_port: 7070
       #jenkins_proxy_port: "{{ apache_listen_port }}" #TODO why is it needed!!!
       phpmyadmin_mysql_user: root
       phpmyadmin_mysql_password: microsoft
       phpmyadmin_mysql_port: "{{ apache_listen_port }}"
       php_date_timezone: "Europe/Paris"
       mysql_innodb_log_file_size: "5M"
       mysql_root_username: root
       mysql_root_password: microsoft
       docker_files_enable: yes
       docker_files_generated_directory: "../roles/alban.andrieu.web"

- name: Install pagespeed
  hosts: apache-servers
  remote_user: albandri

  roles:
    - role: alban.andrieu.pagespeed

  vars:
       apache_listen_port: 7070
       pagespeed_package_arch: "amd64"

- name: Install evasive
  hosts: apache-servers
  remote_user: albandri

  roles:
    - role: alban.andrieu.evasive

  vars:
       apache_listen_port: 7070

- name: Install awstats
  hosts: apache-servers
  remote_user: albandri

  roles:
    - role: alban.andrieu.awstats

  vars:
       apache_listen_port: 7070

- include: jenkins-master.yml

- include: jenkins-slave.yml

- include: maven.yml
       
- name: Install css
  hosts: css
  remote_user: albandri


  roles:
    - alban.andrieu.css

  vars:
#       ruby_version: 2.3.1
       ruby_version: "2.2"

- name: Install chrome
  hosts: chrome
  remote_user: albandri


  roles:
     - role: chrome

  vars:
       google_talkplugin_enabled: yes                       # Enable module
       google_agent_pkg_state: installed # Package states: present or installed or latest

- name: Install nodejs
  hosts: nodejs
  remote_user: albandri


  roles:
    - nodejs

  vars:
       nodejs_install_packages: false
       nodejs_global_packages: []

- name: configure supervisor
  hosts: supervisors
  remote_user: albandri

  roles:
    - role: supervisor

# start a basic python http server on port 8000
  vars:
      name: webserver
      command: python -m SimpleHTTPServer 8000
      directory: /opt/test
# user is the same as base_admin_username
      user: root
      stopsignal: HUP

#- name: configure supervisor
#  hosts: supervisors
#  remote_user: albandri
#
#  roles:
#    - role: supervisor
#      name: fitness
#      command: /workspace/xebium/run.sh
#      directory: /workspace/xebium
## user is the same as base_admin_username
#      user: ubuntu

- include: sonar.yml

#Below cmake conky is included in workstation role
#- name: Install conky
#  hosts: workstation
#  remote_user: albandri
#
#  roles:
#    - role: alban.andrieu.conky

- name: Install git
  hosts: workstation
  remote_user: albandri


  roles:
    - role: geerlingguy.git

- name: Install subversion
  hosts: workstation
  remote_user: albandri


  roles:
    - role: alban.andrieu.subversion

  vars:
      subversion_owner: "{{ user }}"
      subversion_group: "{{ group }}"

- name: Apply common shell configuration
  hosts: workstation
#  remote_user: root
  remote_user: albandri

#  become: yes

  roles:
    - role: alban.andrieu.shell

  vars:
    shell_default_version: "30"
    shell_git_configure_enabled: yes
    shell_git:
      # Additional properties: 'shell_git_machine, shell_git_login, shell_git_email, shell_git_password, shell_git_name, shell_git_path, shell_git_ssl'.
         - {
           shell_git_machine: '82.231.208.223',
           shell_git_login: 'AlbanAndrieu',
           shell_git_email: 'alban.andrieu@free.fr',
           shell_git_password: 'microsoft',
           shell_git_name: "Andrieu, Alban",
           shell_git_path: '/usr/bin',
           shell_git_ssl: false,
           shell_git_meld_enabled: yes,
           shell_git_editor: "gedit"
           }
#         - {
#           shell_git_machine: 'https://github.com',
#           shell_git_login: 'AlbanAndrieu',
#           shell_git_email: 'alban.andrieu@free.fr',
#           shell_git_password: 'microsoft',
#           shell_git_name: "Andrieu, Alban",
#           shell_git_path: '/usr/bin',
#           shell_git_ssl: false,
#           shell_git_meld_enabled: yes,
#           shell_git_editor: "gedit"
#           }
#         - {
#           shell_git_machine: 'https://bitbucket.org',
#           shell_git_login: 'AlbanAndrieu',
#           shell_git_email: 'alban.andrieu@free.fr',
#           shell_git_password: 'microsoft',
#           shell_git_name: "Andrieu, Alban",
#           shell_git_path: '/usr/bin',
#           shell_git_ssl: false,
#           shell_git_meld_enabled: yes,
#           shell_git_editor: "gedit"
#           }
#      shell_rlogin_enabled: no
    shell_maven_enabled: no
    newrelic_license_key: de35bf5d191ebb208d359b2cd24a60616a02b1f3
    docker_files_enable: no
#    docker_files_generated_directory: "../roles/alban.andrieu.shell"

#- name: Install eclipse

#  hosts: workstation
#  remote_user: albandri
#
#  roles:
#    - role: alban.andrieu.eclipse
#
#  vars:
#      docker_files_generated_directory: "../roles/alban.andrieu.eclipse"
#      docker_files_enable: yes
#      #eclipse_base_dir: /workspace/eclipse
#      #user: "albandri"
#      #home: "/workspace/users/albandri10"

- include: zap.yml

- include: jmeter.yml

- name: Install mon
  hosts: workstation
  remote_user: albandri


  roles:
    - alban.andrieu.mon

  vars:
      apache_listen_port: 7070
      mon_localhost : "albandri"
      mon_custom_group: "nabla"
      mon_admin_email: "alban.andrieu@free.fr"
      mon_weekly_email: "team@free.fr"
      user: root
      home: "/root"

- include: jdiskreport.yml

- include: private-bower.yml

- include: owasp-wte.yml
