
- name: Install java certificate for java
  hosts: RedHat-7*:RedHat-6*:RedHat-5*:CentOS-7*:CentOS-6*
  remote_user: root
  become: yes

  roles:
#    - role: java.certificate
#      java_certificate_host: mail.google.com
#      java_certificate_port: 443

#    - role: java.certificate
#      java_certificate_host: nbala.freeboxos.fr
#      java_certificate_port: 443
#
#    - role: java.certificate
#      java_certificate_host: home.nabla.mobi
#      java_certificate_port: 443

#sonar
#    - role: java.certificate
#      java_certificate_host: home.nabla.mobi
#      java_certificate_port: 8999

    - role: java.certificate
      ignore_errors: yes
      java_path: "/usr/java/latest/"
      java_certificate_host: google.com
      java_certificate_port: 443

    - role: java.certificate
      ignore_errors: yes
      java_path: "/usr/java/latest/"
      java_certificate_host: github.com
      java_certificate_port: 443

- name: Install java certificate for java
  hosts: Ubuntu-18*:Ubuntu-17*:Ubuntu-16*:Ubuntu-14*:Ubuntu-13*:Ubuntu-12*
  remote_user: root
  become: yes

  roles:

#Default standard oracle java 8
    - role: java.certificate
      ignore_errors: yes
      java_path: "/usr/lib/jvm/java-8-oracle/"
      java_certificate_host: google.com
      java_certificate_port: 443

    - role: java.certificate
      ignore_errors: yes
      java_path: "/usr/lib/jvm/java-8-oracle/"
      java_certificate_host: github.com
      java_certificate_port: 443

#Default standard oracle java 7
    - role: java.certificate
      ignore_errors: yes
      java_path: "/usr/lib/jvm/java-7-oracle/"
      java_certificate_host: google.com
      java_certificate_port: 443

    - role: java.certificate
      ignore_errors: yes
      java_path: "/usr/lib/jvm/java-7-oracle/"
      java_certificate_host: github.com
      java_certificate_port: 443

#Dependency check
    - role: java.certificate
      ignore_errors: yes
      java_path: "/usr/lib/jvm/java-8-oracle/"
      java_certificate_host: api.nodesecurity.io
      java_certificate_port: 443
