
# Below is no more needed for ubuntu-19 and docker 19.03.3
- hosts: Ubuntu-18*:Ubuntu-17*:Ubuntu-16*:Ubuntu-14*:Ubuntu-12*

  tasks:
    - name: Get the Docker root certificate
      shell: |
        set -o pipefail
        openssl s_client -showcerts -connect registry.albandrieu.com:443 </dev/null 2>/dev/null | openssl x509 -outform PEM | tee ~/pki/registry.pem
      args:
        executable: /bin/bash
      changed_when: false
      become: true
      become_user: root
      ignore_errors: yes

# Below is no more needed for ubuntu-19 and docker 19.03.3
- hosts: Ubuntu-18*:Ubuntu-17*:Ubuntu-16*:Ubuntu-14*:Ubuntu-12*
  become: true
  check_mode: no
  ignore_errors: yes
  remote_user: root

#See /root/pki/docker.pem
  roles:
    - role: ssl-ca-certificate
      trust_ca_pki_dir: '~/pki'
      trust_ca_pki_prefix: 'registry'
      trust_ca_cert_prefix: 'registry'

#TODO secure docker https://docs.docker.com/engine/security/https/
#mkdir -pv ~/.docker
#cp -v {ca,registry,cert,key}.pem ~/.docker
#docker --tlsverify ps

# Below is no more needed for ubuntu-19 and docker 19.03.3
- hosts: Ubuntu-18*:Ubuntu-17*:Ubuntu-16*:Ubuntu-14*:Ubuntu-12*

  tasks:
    - name: Create .docker
      file: path=~/.docker state=directory mode=0700
      become: true
      become_user: root

    #- name: Copy docker registry pem crt
    #  copy:
    #    src: ~/pki/registry.pem
    #    dest: "{{ item }}"
    #    remote_src: yes
    #  with_items:
    #    - ~/.docker/registry.crt
    #    - /etc/docker/certs.d/registry.albandrieu.com/registry.crt
    #  become: true
    #  become_user: root

    - name: Create registry
      file: path=/etc/docker/certs.d/registry.albandrieu.com/ state=directory mode=0700
      become: true
      become_user: root

    - name: Copy ca pem crt
      copy:
        src: ~/pki/ca.pem
        dest: "{{ item }}"
        remote_src: yes
      with_items:
        - ~/.docker/ca.crt
        - /etc/docker/certs.d/registry.albandrieu.com/ca.crt
      become: true
      check_mode: no
      ignore_errors: yes
      become_user: root
