#ansible-playbook -i hosts-albandri -v certificate.yml -c local --limit albandri-laptop-work --ask-become-pass -vvvv | tee setup.log

- hosts: jenkins-slaves
  remote_user: root

  tasks:

    #- name: Create private key
    #  shell: ssh-keygen -t rsa -C "alban.andrieu@free.fr"
    #  ignore_errors: yes
    #  become: true
    #  become_user: albandri

    - name: Create ~/pki
      file: path=~/pki/ state=directory mode=0700
      become: true
      become_user: root

    #- name: Get the CA root certificate
    #  get_url: dest=~/pki/ca.pem url=http://albandrieu.com:7072/download/certs/NABLA.crt
    #  ignore_errors: yes
    #  become: true
    #  become_user: root

    - name: Get the server DER certificate
      get_url: dest=~/pki/{{ ansible_fqdn }}-der.cer url=http://albandrieu.com:7072/download/certs/servers/{{ ansible_fqdn }}-der.cer
      ignore_errors: yes
      become: true

    - name: Convert DER certificate to PEM
      command: openssl x509 -inform DER -outform PEM -in ~/pki/{{ ansible_fqdn }}-der.cer -out /etc/ssl/{{ ansible_fqdn }}/{{ ansible_fqdn }}.pem
      ignore_errors: yes
      changed_when: false
      become: true

- import_playbook: certificate-server.yml

- import_playbook: certificate-docker.yml

- import_playbook: certificate-java.yml
