
- name: Install java certificate for java
  hosts: RedHat-7*:RedHat-6*:RedHat-5*:CentOS-7*:CentOS-6*
  remote_user: root
  become: true

  roles:
#    - role: java-certificate
#      java_certificate_host: mail.google.com
#      java_certificate_port: 443

#    - role: java-certificate
#      java_certificate_host: nbala.freeboxos.fr
#      java_certificate_port: 443
#
#    - role: java-certificate
#      java_certificate_host: home.nabla.mobi
#      java_certificate_port: 443

# Sonar
#    - role: java-certificate
#      java_certificate_host: home.nabla.mobi
#      java_certificate_port: 8999

    - role: java-certificate
      ignore_errors: true
      java_path: "/usr/java/latest/"
      java_certificate_host: google.com
      java_certificate_port: 443

    - role: java-certificate
      ignore_errors: true
      java_path: "/usr/java/latest/"
      java_certificate_host: github.com
      java_certificate_port: 443

- name: Install java certificate for java
  hosts: Ubuntu-18*:Ubuntu-17*:Ubuntu-16*:Ubuntu-14*:Ubuntu-13*:Ubuntu-12*
  remote_user: root
  become: true

  roles:

# Default standard oracle java 8
    - role: java-certificate
      ignore_errors: true
      java_path: "/usr/lib/jvm/java-8-oracle/"
      java_certificate_host: google.com
      java_certificate_port: 443

    - role: java-certificate
      ignore_errors: true
      java_path: "/usr/lib/jvm/java-8-oracle/"
      java_certificate_host: github.com
      java_certificate_port: 443

# Dependency check
    - role: java-certificate
      ignore_errors: true
      java_path: "/usr/lib/jvm/java-8-oracle/"
      java_certificate_host: api.nodesecurity.io
      java_certificate_port: 443

# Default standard openjdk java 8
# /usr/lib/jvm/java-8-openjdk-amd64/ java-openjdk
    - role: java-certificate
      ignore_errors: true
      java_path: "/usr/lib/jvm/java-openjdk"
      java_certificate_host: google.com
      java_certificate_port: 443

    - role: java-certificate
      ignore_errors: true
      java_path: "/usr/lib/jvm/java-openjdk"
      java_certificate_host: github.com
      java_certificate_port: 443

# Dependency check
    - role: java-certificate
      ignore_errors: true
      java_path: "/usr/lib/jvm/java-openjdk"
      java_certificate_host: api.nodesecurity.io
      java_certificate_port: 443
