
- name: Install java certificate for java 7 and 8
  hosts: workstation
  remote_user: albandri
  become: yes

  roles:
#    - role: java.certificate
#      java_certificate_host: mail.google.com
#      java_certificate_port: 443

#    - role: java.certificate
#      java_certificate_host: nbala.freeboxos.fr
#      java_certificate_port: 443
#
#    - role: java.certificate
#      java_certificate_host: home.nabla.mobi
#      java_certificate_port: 443

#sonar
#    - role: java.certificate
#      java_certificate_host: home.nabla.mobi
#      java_certificate_port: 8999

    - role: java.certificate
      java_certificate_host: google.com
      java_certificate_port: 443

    - role: java.certificate
      java_certificate_host: github.com
      java_certificate_port: 443

#Default standard oracle java 8
    - role: java.certificate
      ignore_errors: yes
      java_path: "/usr/lib/jvm/java-8-oracle/"
      java_certificate_host: google.com
      java_certificate_port: 443

    - role: java.certificate
      ignore_errors: yes
      java_path: "/usr/lib/jvm/java-8-oracle/"
      java_certificate_host: github.com
      java_certificate_port: 443

#Default standard oracle java 7
    - role: java.certificate
      ignore_errors: yes
      java_path: "/usr/lib/jvm/java-7-oracle/"
      java_certificate_host: google.com
      java_certificate_port: 443

    - role: java.certificate
      ignore_errors: yes
      java_path: "/usr/lib/jvm/java-7-oracle/"
      java_certificate_host: github.com
      java_certificate_port: 443

#Dependency check
    - role: java.certificate
      ignore_errors: yes
      java_path: "/usr/lib/jvm/java-8-oracle/"
      java_certificate_host: api.nodesecurity.io
      java_certificate_port: 443
