---

- name: Install CA root certificate
  hosts: certificate_server
  gather_facts: false
  remote_user: root
  check_mode: no
  ignore_errors: yes
  become: true

  roles:
    - role: ssl-ca-certificate
      trust_ca_pki_dir: '~/pki'

- name: Install server certificate
  hosts: certificate_server
  become: true

  roles:
    - role: ssl-certificate
      ssl_certs_country: "FR"
      ssl_certs_locality: "Paris"
      ssl_certs_organization: "Nabla"
      ssl_certs_state: "Ile de France"
      #ssl_certs_common_name: "{{ ansible_fqdn }}"
      ssl_certs_domain_name: "int.albandrieu.com"
      ssl_certs_san_name: "vaultuat.{{ ssl_certs_domain_name }}"
      ssl_certs_common_name: "{{ ansible_hostname }}.{{ ssl_certs_domain_name }}"
      ssl_certs_email: "alban.andrieu@free.fr"
      ssl_certs_days: "3650"
      ssl_certs_fields: "/C={{ ssl_certs_country }}/ST={{ ssl_certs_state }}/L={{ ssl_certs_locality }}/O={{ ssl_certs_organization }}/CN={{ ssl_certs_common_name }}/emailAddress={{ ssl_certs_email }}/subjectAltName=DNS.1={{ ssl_certs_common_name },DNS.2={{ ansible_fqdn }},DNS.3={{ ansible_hostname }},DNS.4=localhost,IP={{ ansible_default_ipv4.address }},IP=127.0.0.1" # noqa 204
      #ssl_certs_path_owner: "root"
      #ssl_certs_path_group: "root"
      #ssl_certs_mode: 700
