#sudo ansible-playbook -i hosts-albandri -c local -v chrome.yml | tee setup.log

- name: Install chrome
  connection: local
  hosts: workstation
#  remote_user: root
#  accelerate: true

  roles:
    - { role: chrome,
        google_talkplugin_enabled: yes,
        google_agent_pkg_state: installed # Package states: present or installed or latest
      }    
