---

- name: Install chrome
  hosts: jenkins-slaves
  become: true
#  accelerate: true

  roles:
     - role: chrome
       google_talkplugin_enabled: false
       google_agent_pkg_state: installed # Package states: present or installed or latest
