---

- name: Install chrome
  hosts: jenkins-slaves
  become: true

  roles:
     - role: devbox.chrome
       google_talkplugin_enabled: false
       google_agent_pkg_state: installed # Package states: present or installed or latest
