#sudo rm -Rf /opt/collectd
#sudo rm -Rf /usr/src/collectd-*
#sudo ansible-playbook -i hosts-albandri -c local --limit albandri -v collectd.yml -vvvv --ask-sudo | tee setup.log

- name: Add collectd configuration
  hosts: collectd
  become: true

  roles:
    - collectd

  vars:
       collectd_write_graphite: false
#       collectd_hostname: "{{ inventory_hostname }}"
       collectd_hostname: "albandri"
       #collectd_prefix: "/etc/collectd"
       collectd_type: false
       #collectd_prefix_type: "/usr/share/collectd/"
       #collectd_prefix_conf: "{{ collectd_prefix }}"
       #collectd_prefix_sbin: "/usr/sbin"
       #collectd_prefix_custom_dir: "/usr/lib/collectd"
       collectd_upstart: false # used ubuntu default one
       collectd_plugins: [apache, battery, irq, java, mysql, nginx, memcached]
       collectd_default_plugins: [cpu, df, disk, entropy, interface, load, memory, swap, processes, network, uptime, users]
       collectd_default_plugins_options:
         swap:
         - ReportByDevice false
         interface:
         - Interface lo
         - Interface eth0
         - Interface eth1
         - Interface wlan1
         - Interface docker0
         - IgnoreSelected true
         network:
         - Server 10.25.40.139 25826
       collectd_write_graphite_options:
         Host: localhost
         LogSendErrors: 'true'
