#ansible-playbook -i hosts-albandri -c local -v conky.yml -vvvv --ask-sudo-pass | tee setup.log

- hosts: all
  gather_facts: true
  tasks:
    - name: group hosts by distribution
      group_by: key="{{ ansible_distribution }}-{{ ansible_distribution_version }}"

- hosts: Ubuntu-12*:Ubuntu-13*:Ubuntu-14*:Ubuntu-16*:Ubuntu-17*
  gather_facts: false
  tasks:
    - name: group hosts for supported distributions
      group_by: key="supported"

- hosts: "!supported"
  gather_facts: false
  tasks:
    - name: fail for unsupported distribution
      fail: msg="{{ ansible_distribution }} {{ ansible_distribution_version }}
                 is not a supported OS for a Tower installation.  Supported
                 OSes include Ubuntu 12.04/14.04/16.04/17.04."
    - debug: msg="Version {{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_architecture }}"

# This playbook can be run using vagrant (on virtual box).
- name: Install conky
  hosts: workstation
  remote_user: root
#  connection: local

  roles:
    - role: alban.andrieu.conky

  vars:
       conky_sensor_enabled: yes
       conky_manager_enabled: yes
