#ansible-playbook -i hosts-albandri -c local -v conky.yml -vvvv --ask-become-pass | tee setup.log

# This playbook can be run using vagrant (on virtual box).
- name: Install conky
  hosts: workstation
  remote_user: root
#  connection: local

  roles:
    - role: alban.andrieu.conky

  vars:
       conky_sensor_enabled: yes
       conky_manager_enabled: yes
