---

- name: Install gcc
  hosts: cpp

  roles:
#    - role: alban.andrieu.gcc
#      gcc_version: "=4:9.2.1-3.1ubuntu1" # g++ 9 on ubuntu 19
#      gcc_version: "=4:7.4.0-1ubuntu2.3" # g++ 7 on ubuntu 18
#      gcc_priority: 10

    - role: alban.andrieu.gcc
      gcc_version: "-4.8"
      gcc_priority: 10

    - role: alban.andrieu.gcc
      gcc_version: "-4.9"
      gcc_priority: 20

    - role: alban.andrieu.gcc
      gcc_version: "-5"
      gcc_priority: 50

    - role: alban.andrieu.gcc
      gcc_version: "-6"
      gcc_priority: 60

- name: Install cpp
  hosts: cpp

  roles:
    - alban.andrieu.cpp

  vars:
      #cppunit_version: "-1.13-0"
      cppunit_version: "-1.13-0v5"
      #boost_version: "1.54"
      #boost_version: "1.58"
      boost_version: "1.61"
      #clang_version: "-4.0"
      #clang_version: "=1:6.0-41~exp5~ubuntu1" # clang 6 on ubuntu 18
      clang_version: "=1:9.0-49~exp1" # clang 9 on ubuntu 19
      cpp_package_list: []
