---

- name: Install gcc
  hosts: cpp
#  connection: local
#  remote_user: root

  roles:
#    - role: alban.andrieu.gcc
#      gcc_version: "=4:4.8.2-1ubuntu6"
#      gcc_priority: 10

    - role: alban.andrieu.gcc
      gcc_version: "-4.8"
      gcc_priority: 10

    - role: alban.andrieu.gcc
      gcc_version: "-4.9"
      gcc_priority: 20

    - role: alban.andrieu.gcc
      gcc_version: "-5"
      gcc_priority: 50

    - role: alban.andrieu.gcc
      gcc_version: "-6"
      gcc_priority: 60

- name: Install cpp
  hosts: cpp
#  connection: local
#  remote_user: root

  roles:
    - alban.andrieu.cpp

  vars:
      #cppunit_version: "-1.13-0"
      cppunit_version: "-1.13-0v5"
      #boost_version: "1.54"
      #boost_version: "1.58"
      boost_version: "1.61"
      clang_version: "-4.0"
      cpp_package_list: []
