#sudo ansible-playbook -i hosts-albandri -c local -v dns.yml | tee setup.log

- name: Apply dns configuration to all nodes
#  hosts: Ubuntu-12*:Ubuntu-14*
  hosts: workstation
  gather_facts: false
  remote_user: root
#  connection: local

  roles:
    - alban.andrieu.dns

  vars:
       defaultdomain: nabla.global.ad
       search: nabla.global.ad nabla.freeboxos.fr freeboxos.fr home.nabla.mobi nabla.mobi
       dns_nameservers:
         - "8.8.8.8" # google dns
         - "8.8.4.4" # google dns
         - "192.168.1.254" #freebox
         - "212.27.40.240" #free
         - "212.27.40.241" #free   
         - "10.25.200.3" # work dns
         - "10.21.200.3" # work dns
#paris
#      nameserver1: 10.21.200.3
#      nameserver2: 10.25.200.3
#gdynia
#      nameserver1: 10.7.109.27
#      nameserver2: 10.7.111.244
