---

- name: Apply dns configuration to all nodes
  hosts: docker
  gather_facts: false
  remote_user: root

  roles:
    - albanandrieu.dns

  vars:
       defaultdomain: albandrieu.com
       search: albandrieu.com
       defaultsearch: int.nabla.com odfe.nabla.com consul albandrieu.com home
       dns_nameservers:
         - "10.20.0.33" # work adguardhome freenas
         #- "10.21.200.2" # work dns
         #- "10.41.200.3" # work dns
         - "8.8.8.8" # google dns
         - "8.8.4.4" # google dns
         #- "192.168.1.1" # orange dns
#         - "192.168.0.254" # freebox dns
         - "80.10.246.136" # wanadoo dns
#         - "212.27.40.240" #free
#         - "212.27.40.241" #free
         - "192.168.1.1" #debian
         - "192.168.1.2" #debian
#paris
#      nameserver1: 10.21.200.3
#      nameserver2: 10.25.200.3
#gdynia
#      nameserver1: 10.7.109.27
#      nameserver2: 10.7.111.244
