#ansible-playbook -i hosts -v docker.yml --limit albandri --ask-sudo-pass -vvvv | tee setup.log

- hosts: all
  gather_facts: true
  tasks:
    - name: group hosts by distribution
      group_by: key="{{ ansible_distribution }}-{{ ansible_distribution_version }}"

- hosts: RedHat-7*:RedHat-6*:RedHat-5*:CentOS-7*:CentOS-6*:Ubuntu-18*:Ubuntu-17*:Ubuntu-16*:Ubuntu-14*:Ubuntu-13*:Ubuntu-12*
  gather_facts: false
  tasks:
    - name: group hosts for supported distributions
      group_by: key="supported"

- hosts: "!supported"
  gather_facts: false
  tasks:
    - name: fail for unsupported distribution
      fail: msg="{{ ansible_distribution }} {{ ansible_distribution_version }}
                 is not a supported OS for a Tower installation.  Supported
                 OSes include Red Hat Enterprise Linux 6/7, CentOS 6/7, or
                 Ubuntu 12.04/13.04/14.04/16.04/17.04/18.04."
    - debug: msg="Version {{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_architecture }}"

#- hosts: docker
#  become: yes
#  pre_tasks:
#  - name: Log into DockerHub
#    docker_login:
#      username: nabla
#      password: todo
#      email: alban.andrieu@free.fr

- import_playbook: docker-ubuntu.yml

#https://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo
#sudo groupadd docker
#sudo gpasswd -a ${USER} docker
#sudo gpasswd -a jenkins docker

- name: Run docker.ubuntu
#  hosts: RedHat-7*:RedHat-6*:RedHat-5*:CentOS-7*:CentOS-6*
  hosts: docker
  become: yes

  roles:
  - docker
  # vars:
  #   docker_ce_version: "17.09.1~ce-0~ubuntu"

- hosts: docker
  become: yes

  tasks:
    - name: Create a docker group
      group:
          name=docker
          state=present
      become: yes
      ignore_errors: true

    - name: Add user(s) to docker group
      user:
          name="{{ lookup('env','USER') }}"
          group=docker
          state=present
      become: yes
      ignore_errors: true

    - name: Add user(s) to docker group
      user:
          name="{{ remote_user|default('jenkins') }}"
          group=docker
          state=present
      become: yes
      ignore_errors: true
