#ansible-playbook -i production -c local -v docker-cleaning.yml --ask-pass -vvvv | tee setup.log
#ansible-playbook -i production -c local -v docker-cleaning.yml --limit albandri --ask-become-pass -vvvv | tee setup.log

- hosts: docker-cleaning
  become: true

  tasks:
#    - name: Log into private registry and force re-authorization
#      docker_login:
#        registry: https://docker.nabla.mobi/
#        username: nabla
#        password: microsoft
#        reauthorize: yes

- hosts: docker-cleaning
  become: true

  tasks:
    - name: Remove ubuntu image
      docker_image:
        state: absent
        name: ubuntu:14.04

    - name: Remove hello-world image
      docker_image:
        state: absent
        name: hello-world:latest
        force: yes

#    - name: Remove test image
#      docker_image:
#        state: absent
#        name: nabla/ansible-jenkins-slave-docker
#        tag: test

#TODO http://blog.yohanliyanage.com/2015/05/docker-clean-up-after-yourself/
#TODD must be run on a daily basis
#Clean 1 week old containers
#docker ps -a | grep 'weeks ago' | awk '{print $1}' | xargs --no-run-if-empty docker rm
#Clean all containers
#docker rm `docker ps --no-trunc -aq`

# TODO below might be useless
    - name: Remove unwanted dangling images
      shell: "docker rmi $(docker images -f \"dangling=true\" -q)"
      ignore_errors: true
      changed_when: false

# TODO below might be useless
    - name: Remove unwanted ‘dangling’ volumes
      shell: "docker volume rm $(docker volume ls -qf dangling=true)"
      ignore_errors: true
      changed_when: false

    - name: Remove hanging and old fusion-risk docker images
      shell: "docker kill $(docker ps | grep -E 'Up [0-9]+ days' | awk '{print $1}') ; docker rmi $(docker image ls | grep -i nabla | grep -E 'days|weeks|months ago' | grep -v jenkins-slave | awk '{print $3}')"
      ignore_errors: true
      changed_when: false

    - name: Pull ansible-jenkins-slave-docker latest images
      docker_image:
        name: nabla/ansible-jenkins-slave-docker
        tag: latest

    - name: Check images is fully available
      shell: "docker inspect -f . nabla/ansible-jenkins-slave-docker:latest"
      changed_when: false

#docker ps -a -s
#docker images
