#ansible-playbook -i staging -c local -v docker-registry.yml --ask-pass -vvvv | tee setup.log
#ansible-playbook -i staging -c local -v docker-registry.yml --limit albandri --ask-sudo-pass -vvvv | tee setup.log

- hosts: all
  gather_facts: true
  tasks:
    - name: group hosts by distribution
      group_by: key="{{ ansible_distribution }}-{{ ansible_distribution_version }}"

- hosts: RedHat-7*:RedHat-6*:RedHat-5*:CentOS-7*:CentOS-6*:Ubuntu-17*:Ubuntu-16*:Ubuntu-14*:Ubuntu-13*:Ubuntu-12*
  gather_facts: false
  tasks:
    - name: group hosts for supported distributions
      group_by: key="supported"

- hosts: "!supported"
  gather_facts: false
  tasks:
    - name: fail for unsupported distribution
      fail: msg="{{ ansible_distribution }} {{ ansible_distribution_version }}
                 is not a supported OS for a Tower installation.  Supported
                 OSes include Red Hat Enterprise Linux 6/7, CentOS 6, or
                 Ubuntu 12.04/13.04/14.04/16.04/17.04."
    - debug: msg="Version {{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_architecture }}"

- hosts: docker-container-oracle

  tasks:
#    - name: Log into private registry
#      docker_login:
#        registry: https://docker.nabla.mobi/
#        username: nabla
#        password: microsoft
#        state: present
#        debug: true
##        reauthorize: yes
##        ignore_errors: true

    - name: Inspect multiple images
      docker_image_facts:
        name:
          - database-instantclient
          - database-enterprise

- hosts: docker-container-oracle
#  become: yes

  tasks:
    - name: Pull database-instantclient images
      docker_container:
        name: database-instantclient
        image: store/oracle/database-instantclient:12.2.0.1
        state: present
        recreate: false
        #pull: yes
        #command: sleep infinity

    - name: Pull database-enterprise images
      docker_container:
        name: database-enterprise
        #image: store/oracle/database-enterprise:12.2.0.1
        image: registry.misys.global.ad/misys-common/oracle-database:12.1.0.2
        #image: registry.misys.global.ad/fusion-risk/oracle:12.2.0.1-se2
        state: present
        recreate: false
        #pull: yes
        #command: sleep infinity
