#ansible-playbook -i staging -c local -v docker-registry.yml --ask-pass -vvvv | tee setup.log
#ansible-playbook -i staging -c local -v docker-registry.yml --limit albandri.misys.global.ad --ask-sudo-pass -vvvv | tee setup.log

- hosts: all
  gather_facts: true
  tasks:
    - name: group hosts by distribution
      group_by: key="{{ ansible_distribution }}-{{ ansible_distribution_version }}"

- hosts: RedHat-7*:RedHat-6*:CentOS-6*:Ubuntu-12.04:Ubuntu-14.04:Ubuntu-16.04
  gather_facts: false
  tasks:
    - name: group hosts for supported distributions
      group_by: key="supported"

- hosts: "!supported"
  gather_facts: false
  tasks:
    - name: fail for unsupported distribution
      fail: msg="{{ ansible_distribution }} {{ ansible_distribution_version }}
                 is not a supported OS for a Tower installation.  Supported
                 OSes include Red Hat Enterprise Linux 6/7, CentOS 6, or
                 Ubuntu 12.04/14.04."

- include: docker.yml

#sudo docker logout https://docker.nabla.mobi:5000
#sudo docker login dtr.nabla.mobi:443
- hosts: docker
#  become: yes

  pre_tasks:
    - name: Log into private registry and force re-authorization
      docker_login:
        registry: https://docker:443/
        username: nabla
        password: microsoft
        reauthorize: yes

    - name: Inspect multiple images
      docker_image_facts:
        name:
          - nabla/centos
          - nabla/java

- hosts: docker
#  become: yes

  tasks:
    - name: Remove ubuntu image
      docker_image:
        state: absent
        name: ubuntu:14.04
        
    - name: Remove hello-world image
      docker_image:
        state: absent
        name: hello-world:latest
        force: yes
              
    - name: Remove test image
      docker_image:
        state: absent
        name: docker/test/jenkins-slave
        tag: test
  
    - name: Pull centos images
      docker_container:
        name: centos
        image: docker/nabla/centos:6.8-latest
        state: stopped
        pull: yes
        #command: sleep infinity

    - name: Pull java images
      docker_container:
        name: java
        image: docker/nabla/java
        state: stopped
        pull: yes
        #command: sleep infinity

#TODO http://blog.yohanliyanage.com/2015/05/docker-clean-up-after-yourself/
#TODD must be run on a daily basis
#Clean 1 week old containers
#docker ps -a | grep 'weeks ago' | awk '{print $1}' | xargs --no-run-if-empty docker rm
#Clean all containers
#docker rm `docker ps --no-trunc -aq`

    - name: Clean all exited containers
      shell: "docker rm -v $(docker ps -a -q -f status=exited)"
      ignore_errors: true
      
    - name: Remove unwanted dangling images
      shell: "docker rmi $(docker images -f \"dangling=true\" -q)"
      ignore_errors: true
      
    - name: Remove unwanted ‘dangling’ volumes
      shell: "docker volume rm $(docker volume ls -qf dangling=true)"
      ignore_errors: true
       
#docker ps -a -s
#docker images
