#ansible-playbook -i hosts -v docker.yml --limit albandri --ask-become-pass -vvvv | tee setup.log

#- hosts: docker
#  become: true
#  pre_tasks:
#  - name: Log into DockerHub
#    docker_login:
#      username: nabla
#      password: todo
#      email: alban.andrieu@free.fr

#- import_playbook: docker-ubuntu.yml

#https://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo
#sudo groupadd docker
#sudo gpasswd -a ${USER} docker
#sudo gpasswd -a jenkins docker

- name: Run docker
  hosts: docker
  become: true
  ignore_errors: true
  tags:
    - vm

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  vars:
    docker_install_compose: false # using pip instead
    docker_compose_version: "1.25.0"
     #TODO fix docker version
     #docker_edition: ce
     #docker_version: 18.06.0
     #docker_package: "docker-{{ docker_edition }}-{{ docker_version }}" # CentOS
     #docker_package: "docker-{{ docker_edition }}={{ docker_version }}" # Ubuntu
     #TODO make sure it does not conflit with jenkins-slave python35.yml and requirements-current-3.5.txt
     #pip_install_packages:
     #  - name: docker
     #    version: "2.7.0"
     #    virtualenv: /opt/ansible/env35
     #
     #  # Or uninstall a package.
     #  - name: awscli
     #    state: absent
     #    virtualenv: /opt/ansible/env35
     #
     #  # Or force a reinstall.
     #  - name: docker-compose
     #    version: "1.12.0"
     #    state: forcereinstall
     #    virtualenv: /opt/ansible/env35
     #docker_users:
     #  - docker
     #  - jenkins

- hosts: docker
  become: true
  tags:
    - vm

  tasks:
    - name: Create a docker group
      group:
          name=docker
          state=present
      become: true
      ignore_errors: true

    - name: Add user(s) to docker group
      user:
          name="{{ lookup('env','USER') }}"
          group=docker
          state=present
      become: true
      ignore_errors: true

    - name: Add user(s) to docker group
      user:
          name="{{ remote_user|default('jenkins') }}"
          group=docker
          state=present
      become: true
      ignore_errors: true
