---
#ansible-playbook -i inventory/hosts-albandrieu -c local -v /playbooks/dropbox.yml -vvvv --ask-become-pass | tee setup.log

- name: Install subversion
  connection: local
  hosts: workstation
#  remote_user: albandrieu
#  accelerate: true

  roles:
    - { role: albanandrieu.dropbox,
        docker_files_enable: yes,
        docker_files_generated_directory: "../roles/albanandrieu.dropbox",
        dropbox_owner: "{{ user }}",
        dropbox_group: "{{ group }}",
        #dropbox_user_directory: "/workspace/Dropbox",
        #dropbox_user_directory: "/home/albandrieu/Dropbox",
        dropbox_user_host : "2366450895"
      }
