---

#ansible-playbook -i playbooks/hosts-albandri -c local -v playbooks/eclipse.yml -vvvv --limit albandri | tee setup.log
#ansible-playbook -i playbooks/hosts-albandri -c local -v playbooks/eclipse.yml -vvvv --limit albandri --ask-sudo-pass | tee setup.log

- name: Install eclipse
#  connection: local
  hosts: eclipse
  remote_user: albandri
#  remote_user: root
#  accelerate: true

  roles:
    - alban.andrieu.eclipse

  vars:
       docker_files_enable: no
       docker_files_generated_directory: "../roles/alban.andrieu.eclipse"
       eclipse_plugins_emf_enabled: no
       eclipse_plugins_cdt_enabled: no
       eclipse_plugins_cmakeed_enabled: no
       eclipse_plugins_openinterminal_enabled: no
       eclipse_plugins_protobuf_enabled: no
       eclipse_plugins_yedit_enabled: no
       eclipse_plugins_shelled_enabled: no
       eclipse_plugins_webpageed_enabled: no
       eclipse_plugins_pydev_enabled: no
       eclipse_plugins_m2e_enabled: no
       eclipse_plugins_subclipse_enabled: no
      #eclipse_base_dir: "/workspace/eclipse"
      #eclipse_owner: "{{ user }}"
      #eclipse_group: "{{ eclipse_owner }}"
      #eclipse_owner_home: "{{ home }}"
