---

#ansible-playbook -i inventory/hosts-albandrieu -c local -v playbooks/eclipse.yml -vvvv --limit albandrieu --ask-become-pass | tee setup.log

- name: Install eclipse
#  connection: local
  hosts: eclipse
  remote_user: albandrieu
#  remote_user: root
#  accelerate: true

  roles:
    - albanandrieu.eclipse

  vars:
       docker_files_enable: no
       docker_files_generated_directory: "../roles/albanandrieu.eclipse"
       eclipse_dir_tmp: "/tmp"
       #eclipse_owner: albandrieu
       eclipse_group: docker
       eclipse_plugins_emf_enabled: no
       eclipse_plugins_cdt_enabled: no
       eclipse_plugins_cmakeed_enabled: no
       eclipse_plugins_openinterminal_enabled: no
       eclipse_plugins_protobuf_enabled: no
       eclipse_plugins_yedit_enabled: no
       eclipse_plugins_shelled_enabled: no
       eclipse_plugins_webpageed_enabled: no
       eclipse_plugins_pydev_enabled: no
       eclipse_plugins_m2e_enabled: no
       eclipse_plugins_subclipse_enabled: no
      #eclipse_base_dir: "/workspace/eclipse"
      #eclipse_owner: "{{ user }}"
      #eclipse_group: "{{ eclipse_owner }}"
      #eclipse_owner_home: "{{ home }}"
