#ansible-playbook -i hosts-albandri -c local -v eclipse.yml -vvvv --ask-sudo-pass | tee setup.log

- hosts: all
  gather_facts: true
  tasks:
    - name: group hosts by distribution
      group_by: key="{{ ansible_distribution }}-{{ ansible_distribution_version }}"

- hosts: Ubuntu-12.04:Ubuntu-14.04
  gather_facts: false
  tasks:
    - name: group hosts for supported distributions
      group_by: key="supported"

- hosts: "!supported"
  gather_facts: false
  tasks:
    - name: fail for unsupported distribution
      fail: msg="{{ ansible_distribution }} {{ ansible_distribution_version }}
                 is not a supported OS for a Tower installation.  Supported
                 OSes include Ubuntu 12.04/14.04."
                 
- name: Install eclipse
  connection: local
  hosts: workstation
#  remote_user: root
#  accelerate: true
  roles:
    - { role: alban.andrieu.eclipse,
        docker_files_enable: yes,
        docker_files_generated_directory: "roles/alban.andrieu.eclipse",
        eclipse_plugins_emf_enabled: no,
        eclipse_plugins_cdt_enabled: yes,
        eclipse_plugins_cmakeed_enabled: yes,
        eclipse_plugins_openinterminal_enabled: no,
        eclipse_plugins_protobuf_enabled: no,
        eclipse_plugins_yedit_enabled: yes,
        eclipse_plugins_shelled_enabled: no,
        eclipse_plugins_webpageed_enabled: no,
        eclipse_plugins_pydev_enabled: no,
        eclipse_plugins_m2e_enabled: yes,
        eclipse_plugins_subclipse_enabled: yes        
      }

#  vars:
      #eclipse_base_dir: "/workspace/eclipse"
      #eclipse_owner: "{{ user }}"
      #eclipse_group: "{{ eclipse_owner }}"
      #eclipse_owner_home: "{{ home }}"

