#ansible-playbook -i hosts-albandri -c local -v java.yml -vvvv --ask-sudo-pass | tee setup.log

- name: Install java
  connection: local
  hosts: workstation
#  remote_user: root
#  accelerate: true

  roles:
    - { role: java}    


