---
# Aim of this playbook is to test new npm registry with global configuration
#
# javascript-nexus will not be used for previous compilation tasks (label changed)
# After NPM registry migration is successful, all Javascript slave will be configured using this playbook
- name: Javascript configuration with new NPM registry server
  hosts: jenkins-minimal
  become: true

  roles:
    - role: javascript
      tags: nodejs

  vars:
    npm_nexus_private_npm_url: "https://albandri/nexus/repository/npm_group/"
    npm_nexus_private_npm_data:
      - "; internal dependencies"
      - "; scoped packages are taken after configuration"
      - "@uxp:registry=https://albandri/nexus/repository/npm_internal/"
      - ""
      - "; jenkins generic credentials"
      - "//albandri/nexus/repository/npm_group/:_authToken=NpmToken.1234"
    nodejs_version: "11.12.0"
    npm_global_packages:
#      - analyze-css@0.10.2
      - angular@1.3.15
      - bower@1.8.8
      - casperjs@1.1.4
      - coffee-script@1.10.0
      - connect@1.9.2
      - grunt@1.0.4
      - grunt-cli@1.3.2
    #  - grunt-version-check@0.3.8
      - jshint@2.9.5
      - jsonlint@1.6.2
      - json2csv@4.3.3
    #  - karma@4.0.1
#      - node-sass@3.11.2
      - nsp@3.2.1
#      - phantomjs-prebuilt@2.1.16              # EACCES: permission denied
      - phantomas@1.20.1
      - slimerjs@0.10.3
      - tap-eater@0.0.3
      - webdriver-manager@12.1.7
      - yarn@1.19.1
      - yo@3.1.0
      - newman@4.5.5
      - xunit-viewer@5.1.11
