#sudo ansible-playbook -i hosts-albandri -c local -v jboss.yml | tee setup.log

- name: Install subversion
  hosts: workstation
#  remote_user: root
#  accelerate: true

  roles:
    - { role: alban.andrieu.jboss,
        docker_files_enable: yes,
        docker_files_generated_directory: "../roles/jboss"
      }

