#ansible-playbook -i hosts-albandri -v jboss.yml --limit albandri-laptop-work -c local --ask-become-pass -vvvv | tee setup.log

- name: Install subversion
  hosts: workstation
#  remote_user: root
#  accelerate: true

  roles:
    - { role: albanandrieu.jboss,
        docker_files_enable: yes,
        docker_files_generated_directory: "../roles/jboss"
      }
