---
# ansible-playbook -i inventory/hosts-albandri -c local -v playbooks/jenkins-master.yml --ask-become-pass -vvvv | tee setup.log

- import_playbook: hostname.yml

- import_playbook: python.yml

- import_playbook: administration.yml

- import_playbook: java.yml

- import_playbook: certificate.yml

- name: Apply configuration to jenkins master
  hosts: jenkins-master
  become: true

  roles:
    - jenkins-master

  vars:
      jenkins_user: jenkins
      jenkins_version: 2.289.1
      jenkins_proxy: "" # apache
      jenkins_proxy_hostname: localhost
#      jenkins_ssh_key_file: "{{resources_to}}/resources/jenkins/ssh_key"    # (you can manage remote files with Stouts.resources role)
      jenkins_ssh_key_file: "~/.ssh/id_rsa"
      jenkins_ssh_authorized_keys_fingerprints: # Set known authorized keys for ssh
      # Alban Andrieu
        - "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAIEAio3SOQ9yeK6QfKqSFNKyTasuzjStxWevG1Vz1wgJIxPF+KB0XoMAPD081J+Bzj2LCDRSWisNv2L4xv2jbFxW/Pl7NEakoX47eNx3U+Dxaf+szeWBTryYcDUGkduLV7G8Qncm0luIFd+HDIe/Qir1E2f56Qu2uuBNE6Tz5TFt1vc= Alban"
      jenkins_ssh_fingerprints: # Set known hosts for ssh
        - "bitbucket.org,131.103.20.167 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw=="
        - "github.com,204.232.175.90 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
      jenkins_http_port: 8686
      jenkins_http_host: "{{ ansible_fqdn }}"
      #jenkins_http_host: 127.0.0.1
      #jenkins_proxy_port: 7070
      jenkins_proxy_ssl: true
      jenkins_proxy_ssl_certificate: "{{ jenkins_http_host }}.cer"
      jenkins_proxy_ssl_key: "/etc/ssl/{{ jenkins_http_host }}/almonde-jenkins.key"
      jenkins_home: /jenkins
      restart_policy: unless-stopped
      jenkins_target_home: /jenkins
      jenkins_maxopenfiles: 65535
      #See jenkins tuning https://jenkins.io/blog/2016/11/21/gc-tuning/?utm_source=feedburner&utm_medium=twitter&utm_campaign=Feed%3A+ContinuousBlog+%28Jenkins%29
      #-Xmx8096m -XX:MaxPermSize=2048m -Djava.awt.headless=true -Djava.util.Arrays.useLegacyMergeSort=true -Dhudson.slaves.WorkspaceList=-
      jenkins_java_args:
#        - "-Xms8096m -Xmx16192m"
        - "-Djava.awt.headless=true"
        - "-Djenkins.install.runSetupWizard=false"
#0        - "-Xloggc:$JENKINS_HOME/gc-%t.log -XX:NumberOfGCLogFiles=5 -XX:+UseGCLogFileRotation -XX:GCLogFileSize=20m -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintHeapAtGC -XX:+PrintGCCause -XX:+PrintTenuringDistribution -XX:+PrintReferenceGC -XX:+PrintAdaptiveSizePolicy" #GC Logging
        - "-server -XX:+AlwaysPreTouch"
        #- "-Dorg.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true" # To enable for debug
        #- "-Dorg.jenkinsci.plugins.durabletask.BourneShellScript.FORCE_SHELL_WRAPPER=true" # To enable for debug
        #- "-Dorg.jenkinsci.plugins.durabletask.BourneShellScript.FORCE_BINARY_WRAPPER=true" # To enable for debug
        - "-Dorg.jenkinsci.plugins.gitclient.Git.timeOut=120" #For robot framework
        - "-Dhudson.model.DirectoryBrowserSupport.CSP=\"\""
#        - "-Dhudson.slaves.WorkspaceList=_"
#        - "-Dpermissive-script-security.enabled=true"
#below is default for secure jenkins
#      - "--httpPort=-1 --httpsPort=8383 --httpsKeyStore=/etc/ssl/{{ jenkins_http_host }}/{{ jenkins_http_host }}.jks --httpsKeyStorePassword=changeit"
#        - "-Dhudson.model.ParametersAction.keepUndefinedParameters=false"
#1        - "-XX:-BytecodeVerificationLocal -XX:-BytecodeVerificationRemote -XX:+ReduceSignalUsage -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:-UseLargePagesIndividualAllocation"
#2        - "-XX:+UseG1GC -XX:+UseCompressedClassPointers -XX:+UseCompressedOops"
#3        - "-XX:+UseG1GC -XX:+AlwaysPreTouch -XX:+UseStringDeduplication -XX:+UseCompressedClassPointers -XX:+UseCompressedOops"
#4        - "-XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:+UnlockDiagnosticVMOptions -XX:G1SummarizeRSetStatsPeriod=1" #G1 GC settings
        - "-Dhudson.plugins.git.GitSCM.verbose=true"
#        - "-Dorg.jenkinsci.plugins.docker.workflow.client.DockerClient.CLIENT_TIMEOUT=240" #JAVA_OPTS
      jenkins_prefix: "/jenkins"
      jenkins_system_config:
        admin_email: alban.andrieu@free.fr
##!/usr/bin/groovy
#def pluginList = new ArrayList(Jenkins.instance.pluginManager.plugins)
#pluginList.sort { it.getShortName() }.each{
#  plugin ->
#    //println ("${plugin.getDisplayName()} (${plugin.getShortName()}): ${plugin.getVersion()}")
#  println (" - \"${plugin.getShortName()}\"")
#}
      jenkins_plugins:
        - "Parameterized-Remote-Trigger"
        - "ace-editor"
        - "all-changes"
        - "analysis-collector"
        - "analysis-core"
        - "analysis-model-api"
        - "ansible"
        - "ansicolor"
        - "ant"
        - "antisamy-markup-formatter"
        - "apache-httpcomponents-client-4-api"
        - "aqua-microscanner"
        - "aqua-security-scanner"
        - "aqua-serverless"
        - "async-http-client"
        - "authentication-tokens"
        - "authorize-project"
        - "backup"
        - "badge"
        - "basic-branch-build-strategies"
        - "bitbucket"
        - "bitbucket-approve"
        - "bitbucket-build-status-notifier"
        - "bitbucket-oauth"
        - "bitbucket-pullrequest-builder"
        - "bitbucket-scm-filter-aged-refs"
        - "bitbucket-scm-filter-jira-validator"
        - "bitbucket-scm-trait-commit-skip"
        - "blame-upstream-commiters"
        - "blueocean"
        - "blueocean-autofavorite"
        - "blueocean-bitbucket-pipeline"
        - "blueocean-commons"
        - "blueocean-config"
        - "blueocean-core-js"
        - "blueocean-dashboard"
        - "blueocean-display-url"
        - "blueocean-events"
        - "blueocean-executor-info"
        - "blueocean-git-pipeline"
        - "blueocean-github-pipeline"
        - "blueocean-i18n"
        - "blueocean-jira"
        - "blueocean-jwt"
        - "blueocean-personalization"
        - "blueocean-pipeline-api-impl"
        - "blueocean-pipeline-editor"
        - "blueocean-pipeline-scm-api"
        - "blueocean-rest"
        - "blueocean-rest-impl"
        - "blueocean-web"
        - "bouncycastle-api"
        - "branch-api"
        - "build-environment"
        - "build-failure-analyzer"
        - "build-name-setter"
        - "build-pipeline-plugin"
        - "build-timeout"
        - "build-with-parameters"
        - "built-on-column"
        - "bulk-builder"
        - "categorized-view"
        - "checkmarx"
        - "checkstyle"
        - "chosen-views-tabbar"
        - "claim"
        - "clang-scanbuild"
        - "clang-scanbuild-plugin"
        - "cloud-stats"
        - "cloudbees-bitbucket-branch-source"
        - "cloudbees-folder"
        - "cobertura"
        - "code-coverage-api"
        - "command-launcher"
        - "conditional-buildstep"
        - "config-file-provider"
        - "configurationslicing"
        - "confluence-publisher"
        - "copyartifact"
        - "cppcheck"
        - "cppncss"
        - "credentials"
        - "credentials-binding"
        - "crowd2"
        - "cucumber-reports"
        - "custom-tools-plugin"
        - "cvs"
        - "dashboard-view"
        - "delivery-pipeline-plugin"
        - "dependency-check-jenkins-plugin"
        - "dependency-track"
        - "dependencyanalyzer"
        - "depgraph-view"
        - "discard-old-build"
        - "disk-usage"
        - "display-upstream-changes"
        - "display-url-api"
        - "docker-commons"
        - "docker-java-api"
        - "docker-plugin"
        - "docker-workflow"
        - "doclinks"
        - "downstream-buildview"
        - "doxygen"
        - "drmemory-plugin"
        - "dropdown-viewstabbar-plugin"
        - "durable-task"
        - "email-ext"
        - "email-ext-recipients-column"
        - "emailext-template"
        - "embeddable-build-status"
        - "envinject"
        - "envinject-api"
        - "environment-script"
        - "exclusive-execution"
        - "extended-choice-parameter"
        - "external-monitor-job"
        - "extra-columns"
        - "favorite"
        - "findbugs"
        - "forensics-api"
        - "git"
        - "git-changelog"
        - "git-client"
        - "git-parameter"
        - "git-server"
        - "github"
        - "github-api"
        - "github-autostatus"
        - "github-branch-source"
        - "global-slack-notifier"
        - "google-oauth-plugin"
        - "gradle"
        - "greenballs"
        - "groovy"
        - "groovy-events-listener-plugin"
        - "groovy-postbuild"
        - "h2-api"
        - "handlebars"
        - "handy-uri-templates-2-api"
        - "hipchat"
        - "html5-notifier-plugin"
        - "htmlpublisher"
        - "icon-shim"
        - "inodes-monitor"
        - "ivy"
        - "jackson2-api"
        - "jacoco"
        - "javadoc"
        - "javancss"
        - "jaxb"
        - "jdepend"
        - "jdk-tool"
        - "jenkins-design-language"
        - "jenkins-multijob-plugin"
        - "jira"
        - "jira-steps"
        - "jira-trigger"
        - "job-import-plugin"
        - "jobConfigHistory"
        - "jquery"
        - "jquery-detached"
        - "jquery-ui"
        - "jsch"
        - "junit"
        - "junit-attachments"
        - "kubernetes"
        - "kubernetes-client-api"
        - "kubernetes-credentials"
        - "ldap"
        - "locale"
        - "lockable-resources"
        - "log-parser"
        - "m2-repo-reaper"
        - "m2release"
        - "mailer"
        - "mapdb-api"
        - "matrix-auth"
        - "matrix-combinations-parameter"
        - "matrix-project"
        - "maven-deployment-linker"
        - "maven-info"
        - "maven-plugin"
        - "mercurial"
        - "metrics"
        - "metrics-diskusage"
        - "momentjs"
        - "monitoring"
        - "multi-branch-project-plugin"
        - "multi-slave-config-plugin"
        - "multiple-scms"
        - "nested-view"
        - "nexus-artifact-uploader"
        - "nodejs"
        - "nodelabelparameter"
        - "notification"
        - "oauth-credentials"
        - "ontrack"
        - "openJDK-native-plugin"
        - "packer"
        - "pam-auth"
        - "parallel-test-executor"
        - "parameterized-trigger"
        - "perfpublisher"
        - "periodicbackup"
        - "pipeline-build-step"
        - "pipeline-github-lib"
        - "pipeline-graph-analysis"
        - "pipeline-input-step"
        - "pipeline-maven"
        - "pipeline-milestone-step"
        - "pipeline-model-api"
        - "pipeline-model-declarative-agent"
        - "pipeline-model-definition"
        - "pipeline-model-extensions"
        - "pipeline-multibranch-defaults"
        - "pipeline-npm"
        - "pipeline-rest-api"
        - "pipeline-stage-step"
        - "pipeline-stage-tags-metadata"
        - "pipeline-stage-view"
        - "pipeline-utility-steps"
        - "pitmutation"
        - "plain-credentials"
        - "plugin-usage-plugin"
        - "port-allocator"
        - "prereq-buildstep"
        - "project-stats-plugin"
        - "promoted-builds"
        - "publish-over"
        - "publish-over-ssh"
        - "pubsub-light"
        - "purge-build-queue-plugin"
        - "read-only-configurations"
        - "rebuild"
        - "resource-disposer"
        - "robot"
        - "run-condition"
        - "saferestart"
        - "scm-api"
        - "scm-sync-configuration"
        - "scons"
        - "script-security"
        - "show-build-parameters"
        - "sidebar-link"
        - "simple-theme-plugin"
        - "sitemonitor"
        - "slack"
        - "sonar"
        - "sse-gateway"
        - "ssh-agent"
        - "ssh-credentials"
        - "ssh-slaves"
        - "stashNotifier"
        - "structs"
        - "subversion"
        - "swarm"
        - "tap"
        - "tasks"
        - "thinBackup"
        - "throttle-concurrents"
        - "timestamper"
        - "tmpcleaner"
        - "token-macro"
        - "trilead-api"
        - "upstream-downstream-view"
        - "valgrind"
        - "variant"
        - "versioncolumn"
        - "view-job-filters"
        - "violation-comments-to-stash"
        - "violations"
        - "virtualbox"
        - "warnings"
        - "warnings-ng"
        - "whitesource"
        - "windows-slaves"
        - "workflow-aggregator"
        - "workflow-api"
        - "workflow-basic-steps"
        - "workflow-cps"
        - "workflow-cps-global-lib"
        - "workflow-durable-task-step"
        - "workflow-job"
        - "workflow-multibranch"
        - "workflow-scm-step"
        - "workflow-step-api"
        - "workflow-support"
        - "ws-cleanup"
        - "xcode-plugin"
        - "xvfb"
        - "zap"
        - "zapper"
      jenkins_disabled_plugins: [ 'versioncolumn', 'scm-sync-configuration', 'clamav', 'selenium', 'seleniumrc-plugin', 'selenium-builder', 'svnmerge', 'WebSVN2', 'svn-revert-plugin', 'subversion', 'ec2', 'scons', 'gearman-plugin', 'findbugs', 'checkstyle', 'pmd', 'clover', 'fitnesse' ]
      shell_git:
        - {
          shell_git_machine: "github.com",
          shell_git_login: "AlbanAndrieu",
          shell_git_email: "alban.andrieu@free.fr",
          shell_git_password: "microsoft",
          shell_git_name: "Andrieu, Alban",
          shell_git_maildomain: "free.fr",
          shell_git_path: "/usr/bin",
          shell_git_autocrlf: "input",   # For unix, use true for mingw on windows
          shell_git_longpaths: "true",   # For windows
          shell_git_ssl: "false",
          shell_git_meld_enabled: true,
          shell_git_editor: "gedit"
          }
