---
# Playbook to run automatic configuration (or removal) of Jenkins nodes via REST API
#
# This playbook depends on python requests library, local connection and custom modules
# in the ansible ./library directory. It is best run from repository root, so that
# configuration file (ansible.cfg) is available.
#
# To add or reconfigure host use label state=present, to remove host use state=absent.
# Removing node has to be done only once. Jenkins is configured as the default server.
#
# Usage
# $ ansible-playbook -i inventory/staging playbooks/jenkins_node.yml
# $ ansible-playbook -i inventory/staging -e username=mgr.jenkins -e password=*** playbooks/jenkins_node.yml
- hosts: localhost
  gather_facts: no

  vars_prompt:
  - name: "username"
    prompt: "User which has permissions to create new nodes on Jenkins"
  - name: "password"
    prompt: "Password for Jenkins user"
  tasks:
  - name: Request CSRF token from Jenkins
    jenkins_csrf_token:
      auth:
        username: "{{ username }}"
        password: "{{ password }}"
    register: csrf

  - name: Debug Jenkins-Crumb
    debug:
      msg: "CSRF token: {{ csrf.token }}"

  - name: Reconfigure docker-inside and docker-compose nodes
    jenkins_node:
      hostname: "{{ item }}"
      state: present
      nodeDescription: |
        Node automatically configured by Ansible.
        Do not change configuration manually, use jenkins-node.yml playbook inansible instead.
      labels:
      - docker-inside
      - docker-compose
      - ubuntu16
      numExecutors: 2
      env:
      - key: OS_ARCH
        value: x86Linux
      credentialsId: 001 # jenkins@unix-slaves
      remoteFS: /workspace/slave/
      x_token: "{{ csrf.token }}"
      x_auth:
        username: "{{ username }}"
        password: "{{ password }}"
    with_sequence: start=75 end=82 format=TEST00%i

  - name: Reconfigure docker-more nodes
    jenkins_node:
      hostname: "{{ item }}"
      state: present
      nodeDescription: |
        Node automatically configured by Ansible.
        Do not change configuration manually, use jenkins-node.yml playbook in ansible instead.
        Nodes labeled as docker-perf should be used only for resource intensive tasks, such as docker-compose tests.
      labels:
      - docker-more
      numExecutors: 1
      credentialsId: 0001 # jenkins@unix-slaves
      remoteFS: /workspace/slave/
      x_token: "{{ csrf.token }}"
      x_auth:
        username: "{{ username }}"
        password: "{{ password }}"
    with_items:
    - TEST0001
    - TEST0002

  - name: Delete nodes from Jenkins
    jenkins_node:
      hostname: "{{ item }}"
      state: absent
      x_token: "{{ csrf.token }}"
      x_auth:
        username: "{{ username }}"
        password: "{{ password }}"
    with_items:
    # This are example VM that we no longer use, but the playbook can be run on against any node
    - OLDCRAP
