---
# ansible-playbook -i inventory/hosts-albandri -c local -v playbooks/jenkins-master.yml --ask-become-pass -vvvv | tee setup.log

- import_playbook: hostname.yml

- import_playbook: python.yml

- import_playbook: administration.yml

- import_playbook: java.yml

- import_playbook: certificate.yml

- name: Apply configuration to jenkins master
  hosts: jenkins-master
  become: true

  roles:
    - jenkins-master

  vars:
      jenkins_proxy: "" # apache
      jenkins_user: jenkins
      jenkins_version: 2.204.3
      jenkins_proxy_hostname: localhost
#      jenkins_ssh_key_file: "{{resources_to}}/resources/jenkins/ssh_key"    # (you can manage remote files with Stouts.resources role)
      jenkins_ssh_key_file: "~/.ssh/id_rsa"
      jenkins_http_port: 8686
      #jenkins_http_host: "{{ ansible_fqdn }}"
      jenkins_http_host: 127.0.0.1 
      #jenkins_proxy_port: 7070
      jenkins_proxy_ssl: false
      jenkins_proxy_ssl_certificate: "{{ jenkins_http_host }}.cer"
      jenkins_proxy_ssl_key: "/etc/ssl/{{ jenkins_http_host }}/almonde-jenkins.key"
      jenkins_home: /jenkins
      jenkins_target_home: /jenkins
      jenkins_maxopenfiles: 65535
      #See jenkins tuning https://jenkins.io/blog/2016/11/21/gc-tuning/?utm_source=feedburner&utm_medium=twitter&utm_campaign=Feed%3A+ContinuousBlog+%28Jenkins%29
      #-Xmx8096m -XX:MaxPermSize=2048m -Djava.awt.headless=true -Djava.util.Arrays.useLegacyMergeSort=true -Dhudson.slaves.WorkspaceList=-
      jenkins_java_args:
#        - "-Xms8096m -Xmx16192m"
        - "-Djava.awt.headless=true"
        - "-Djenkins.install.runSetupWizard=false"
#0        - "-Xloggc:$JENKINS_HOME/gc-%t.log -XX:NumberOfGCLogFiles=5 -XX:+UseGCLogFileRotation -XX:GCLogFileSize=20m -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintHeapAtGC -XX:+PrintGCCause -XX:+PrintTenuringDistribution -XX:+PrintReferenceGC -XX:+PrintAdaptiveSizePolicy" #GC Logging
        - "-server -XX:+AlwaysPreTouch"
        - "-Dorg.jenkinsci.plugins.gitclient.Git.timeOut=120" #For robot framework
        - "-Dhudson.model.DirectoryBrowserSupport.CSP=\"\""
#        - "-Dhudson.slaves.WorkspaceList=_"
#        - "-Dpermissive-script-security.enabled=true"
#below is default for secure jenkins
#      - "--httpPort=-1 --httpsPort=8383 --httpsKeyStore=/etc/ssl/{{ jenkins_http_host }}/{{ jenkins_http_host }}.jks --httpsKeyStorePassword=changeit"
#        - "-Dhudson.model.ParametersAction.keepUndefinedParameters=false"
#1        - "-XX:-BytecodeVerificationLocal -XX:-BytecodeVerificationRemote -XX:+ReduceSignalUsage -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:-UseLargePagesIndividualAllocation"
#2        - "-XX:+UseG1GC -XX:+UseCompressedClassPointers -XX:+UseCompressedOops"
#3        - "-XX:+UseG1GC -XX:+AlwaysPreTouch -XX:+UseStringDeduplication -XX:+UseCompressedClassPointers -XX:+UseCompressedOops"
#4        - "-XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:+UnlockDiagnosticVMOptions -XX:G1SummarizeRSetStatsPeriod=1" #G1 GC settings
        - "-Dhudson.plugins.git.GitSCM.verbose=true"
#        - "-Dorg.jenkinsci.plugins.docker.workflow.client.DockerClient.CLIENT_TIMEOUT=240" #JAVA_OPTS
      jenkins_prefix: "/jenkins"
      jenkins_system_config:
        admin_email: alban.andrieu@free.fr
      jenkins_plugins:
        - "ws-cleanup"
        - "envinject"
        - "artifactdeployer"
        - "nodenamecolumn"
        - "summary_report"
        - "docker-commons"
        - "publish-over-cifs"
        - "progress-bar-column-plugin"
        - "thinBackup"
        - "token-macro"
        - "jobConfigHistory"
        - "scons"
        - "downstream-buildview"
        - "clamav"
        - "scm-sync-configuration"
        - "deploy"
        - "naginator"
        - "build-publisher"
        - "sonar"
        - "xvfb"
        - "windows-slaves"
        - "m2release"
        - "git"
        - "scm-api"
        - "maven-repo-cleaner"
        - "ssh-agent"
        - "robot"
        #- "clover"
        - "environment-script"
        - "stepcounter"
        - "plugin-usage-plugin"
        - "jenkins-cloudformation-plugin"
        - "cvs"
        - "jira"
        - "fail-the-build-plugin"
        - "workflow-step-api"
        #- "JiraTestResultReporter"
        - "checkmarx"
        - "selenium"
        - "matrix-combinations-parameter"
        - "jobtype-column"
        - "findbugs"
        - "batch-task"
        - "warnings"
        - "violation-columns"
        - "configurationslicing"
        - "parameterized-trigger"
        - "sounds"
        - "job-exporter"
        - "preSCMbuildstep"
        - "fitnesse"
        - "dashboard-view"
        #- "gearman-plugin"
        - "jquery-ui"
        - "gatling"
        - "job-node-stalker"
        - "favorite"
        - "exclusive-execution"
        - "build-pipeline-plugin"
        - "postbuild-task"
        - "skip-certificate-check"
        - "maven-info"
        #- "crowd2"
        - "disk-usage"
        - "node-iterator-api"
        - "ssh"
        - "stashNotifier"
        - "publish-over-ssh"
        - "sitemonitor"
        - "build-metrics"
        - "distfork"
        - "promoted-builds"
        - "flexible-publish"
        - "selenium-builder"
        - "tasks"
        - "computer-queue-plugin"
        - "saferestart"
        ##- "zaproxy"
        - "throttle-concurrents"
        - "read-only-configurations"
        - "ant"
        - "countjobs-viewstabbar"
        - "email-ext"
        - "credentials"
        - "cobertura"
        - "nodejs"
        - "audit-trail"
        #- "svnpublisher"
        - "text-finder-run-condition"
        - "versioncolumn"
        - "global-build-stats"
        - "mapdb-api"
        - "plot"
        - "jquery"
        #- "svn-tag"
        - "show-build-parameters"
        - "conditional-buildstep"
        ##- "copy-to-slave"
        - "maven-plugin"
        - "view-job-filters"
        ##- "jshint-checkstyle"
        - "rebuild"
        - "matrix-project"
        - "performance"
        - "copyartifact"
        ##- "speaks"
        - "groovy"
        #- "svn-revert-plugin"
        #- "ldap"
        - "claim"
        - "docker-build-step"
        - "join"
        - "tap"
        ##- "hudson-jirareporter-plugin"
        - "nodelabelparameter"
        - "custom-tools-plugin"
        - "ansicolor"
        - "translation"
        - "sidebar-link"
        - "bulk-builder"
        #- "jenkins-jira-issue-updater"
        - "checkstyle"
        - "mttr"
        - "ssh-slaves"
        - "ssh-credentials"
        - "Exclusion"
        - "subversion"
        - "antisamy-markup-formatter"
        - "covcomplplot"
        #- "trac"
        - "testng-plugin"
        - "greenballs"
        - "dropdown-viewstabbar-plugin"
        - "nested-view"
        - "test-stability"
        - "external-monitor-job"
        - "docker-build-publish"
        - "any-buildstep"
        - "project-stats-plugin"
        - "timestamper"
        - "build-name-setter"
        - "build-timeout"
        - "prereq-buildstep"
        - "jacoco"
        - "caliper-ci"
        - "pmd"
        - "lastsuccessversioncolumn"
        #- "ec2"
        - "dry"
        - "dependencyanalyzer"
        - "analysis-collector"
        - "analysis-core"
        ##- "description-setter"
        - "chosen-views-tabbar"
        - "port-allocator"
        - "description-setter"
        - "publish-over-ftp"
        - "groovy-postbuild"
        #- "hudson-apiv2-plugin"
        - "build-environment"
        - "seleniumrc-plugin"
        - "git-client"
        - "authentication-tokens"
        - "monitoring"
        - "text-finder"
        - "extended-choice-parameter"
        - "ftppublisher"
        - "built-on-column"
        - "run-condition"
        - "lastfailureversioncolumn"
        - "mask-passwords"
        - "htmlpublisher"
        - "hp-application-automation-tools-plugin"
        - "project-description-setter"
        - "build-with-parameters"
        #- "svnmerge"
        - "git-parameter"
        - "javadoc"
        - "build-failure-analyzer"
        - "confluence-publisher"
        - "script-security"
        - "html5-notifier-plugin"
        - "violations"
        - "next-executions"
        - "jenkins-multijob-plugin"
        - "matrix-auth"
        - "testInProgress"
        - "copy-data-to-workspace-plugin"
        - "mailer"
        - "next-build-number"
        - "qc"
        - "multiple-scms"
        - "job-import-plugin"
        - "junit"
        - "files-found-trigger"
        - "compact-columns"
        - "build-keeper-plugin"
        - "dependency-check-jenkins-plugin"
        - "pam-auth"
        - "log-parser"
        - "locale"
        - "all-changes"
        #- "WebSVN2"
        #- "SquishPlugin"
        - "slave-status"
      jenkins_disabled_plugins: [ 'versioncolumn', 'scm-sync-configuration', 'clamav', 'selenium', 'seleniumrc-plugin', 'selenium-builder', 'svnmerge', 'WebSVN2', 'svn-revert-plugin', 'subversion', 'ec2', 'scons', 'gearman-plugin', 'findbugs', 'checkstyle', 'pmd', 'clover', 'fitnesse' ]
      shell_git:
        - {
          shell_git_machine: "github.com",
          shell_git_login: "AlbanAndrieu",
          shell_git_email: "alban.andrieu@free.fr",
          shell_git_password: "microsoft",
          shell_git_name: "Andrieu, Alban",
          shell_git_path: "/usr/bin",
          shell_git_ssl: false,
          shell_git_meld_enabled: true,
          shell_git_editor: "gedit"
          }
