---

- name: Install jmeter
  connection: local
  hosts: workstation

  roles:
    - role: albanandrieu.zap

  vars:
      jmeter_plugins_standard_enabled: yes
      jmeter_plugins_extras_enabled: yes
      jmeter_plugins_extraslibs_enabled: yes
      jmeter_plugins_webdriver_enabled: yes
      jmeter_plugins_hadoop_enabled: no
      jmeter_serveragent_enabled: yes
