
- name: Install kubernetes helm
  hosts: kubernetes
  become: true
#  ignore_errors: yes

  roles:
    - andrewrothstein.kubernetes-helm

- name: Install kubectl
  hosts: kubernetes
  become: true
#  ignore_errors: yes

  roles:
    - andrewrothstein.kubectl
