#ansible -m setup mac-jenkins.nabla.mobi -vvvv -i production -vvvv
#ansible-playbook -i production  -v mac.yml --limit mac-jenkins.nabla.mobi --ask-sudo-pass
#ansible-playbook -i production -v jenkins-master.yml -vvvv --ask-sudo-pass --limit mac-jenkins.nabla.mobi

- hosts: all
  gather_facts: true
  tasks:
    - name: group hosts by distribution
      group_by: key="{{ ansible_distribution }}-{{ ansible_distribution_version }}-{{ ansible_architecture }}"

#Solaris-10-sun4u not managed via ansible on purpose
- hosts: MacOSX-10.12*
  gather_facts: false
  tasks:
    - name: group hosts for supported distributions
      group_by: key="supported"

- hosts: "!supported"
  gather_facts: false
  tasks:
    - name: fail for unsupported distribution
      fail: msg="{{ ansible_distribution }} {{ ansible_distribution_version }}
                 is not a supported OS for a Tower installation.  Supported
                 OSes include MacOSX 10"

- name: Apply common configuration to mac nodes
  hosts: mac
  become: yes
  #connection: local

#  vars_files:
#    - default.config.yml

  roles:
    - role: mac-dev-playbook
#    - role: geerlingguy.homebrew
#      tags: ['homebrew']
#    - role: geerlingguy.dotfiles
#      when: configure_dotfiles
#      tags: ['dotfiles']
#    - role: geerlingguy.mas
#      when: mas_installed_apps
#      tags: ['mas']

  vars:
    homebrew_installed_packages:
      # - ansible # Installed via Pip.
      - autoconf
      - bash-completion
      - chromedriver
      - doxygen
      - gettext
      - gifsicle
      - git
      - go
      - gpg
      - hub
      - httpie
      - iperf
      - libevent
      - sqlite
      - mcrypt
      - nmap
      - node
      - nvm
      - ssh-copy-id
      - cowsay
      - readline
      - openssl
      - pv
      - wget
      - wrk
      #- cmake
      - scons
      - gcc
      - lcov
      - gperf
      - llvm
      - clang-format
      - mingw-w64
      - gnustep-make
      - cppcheck
      - shellcheck
      - flawfinder
      - rats
      - findbugs
      - ansible-lint
      - bison
      - flex
      - openssl
      - ant
      - maven
      - svn
      - unixodbc
#brew rm unixodbc && brew rm freetds
      - libtool
#brew installink libtool
      - freetds --with-unixodbc
      - md5sha1sum
      - zabbix --without-server-proxy
#Below todo in default.config.yml disable homebrew/php
    homebrew_taps:
      - homebrew/core
      - caskroom/cask
#      - homebrew/php

- hosts: mac

  post_tasks:
   - name: macport | Install macport package (Darwin based)
     action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }}"
     when: (ansible_distribution == 'MacOSX')
     tags: package
     with_items:
      - wget
      - openssl
     changed_when: false

#- import_playbook: jenkins-master.yml
