#ansible-playbook -i hosts-albandri -c local -v maven.yml -vvvv --ask-sudo-pass | tee setup.log

- name: Install maven
  connection: local
  hosts: workstation
#  remote_user: root
#  accelerate: true

  roles:
    - { role: maven}


