---
#as albandri
#ansible-playbook opencl.yml -i hosts-production --limit pricer.nabla.mobi -vvvv --ask-become-pass

#TODO service lightdm stop
# pkill -u jenkins
# pkill -u jenkins-bm

- hosts: opencl
  become: true
  remote_user: root

  pre_tasks:
    - name: Set cpu_driver
      set_fact:
       cpu_driver: "{% if 'GenuineIntel' in ansible_processor %}intel{% elif 'AuthenticAMD' in ansible_processor %}amd{%else%}unknown{%endif%}"

    - debug: msg="{{ cpu_driver }}"

    - name: Get dkms status
      command: "dkms status"
      changed_when: false

#Remove older nvidia driver from kernel
    #modprobe -v nvidia-uvm
    #dpkg -l | grep nvidia
    #apt-get remove nvidia-*
    #apt-get purge nvidia-304

- name: Configure opencl
  hosts: opencl
  become: true
  remote_user: root
  ignore_errors: true
  #connection: local

  roles:
    - opencl

  vars:
    nvidia_driver_version: 352.41
    #nvidia_driver_version: 304.132
    base_url: "http://albandrieu.com/download/opencl"
    kmod_install: true

    #modprobe -v nvidia-uvm

#cat /proc/driver/nvidia/version

#sudo update-alternatives --config opencl-intel-runtime
