---

- name: Install pagespeed
  hosts: apache-servers
  remote_user: root

  roles:
    - role: alban.andrieu.pagespeed

  vars:
       apache_listen_port: 7070
       pagespeed_package_arch: "amd64"
