#sudo ansible-playbook -i hosts-albandri -c local -v phpvirtualbox.yml | tee setup.log

#- import_playbook: lamp.yml

- name: Install phpvirtualbox
  connection: local
  hosts: workstation
#  remote_user: root
#  accelerate: true

  roles:
    - { role: albanandrieu.phpvirtualbox,
        virtualbox_extension_enable: yes,
        phpvirtualbox_owner_password: "microsoft",
        apache_listen_port: 7070,
        #jenkins_proxy_port: "{{ apache_listen_port }}" #TODO why is it needed!!!
        #mysql_user_home: '/home/{{ user }}'
        #phpvirtualbox_install_dir: '/var/www/wordpress',
        phpvirtualbox_apache_listen_port: '{{ apache_listen_port }}',
        phpvirtualbox_apache_hostname: 'phpvirtualbox',
        phpvirtualbox_apache_alias: 'localhost',
        phpvirtualbox_apache_admin_email: 'admin@example.com'
      }
