#sudo ansible-playbook -i hosts-albandri -c local -v python.yml --limit albandri.misys.global.ad --ask-pass | tee setup.log

- name: Install python
  connection: local
  hosts: workstation
#  remote_user: root
#  accelerate: true

  roles:
    - python

  vars:
    python_versions: [2.7, 3.5]
    python_install: [numpy, pandas]
    python_virtualenvs:
      - path: /opt/test/env
