#ansible-playbook -i hosts-albandri -c local -v ruby.yml -vvvv --ask-become-pass | tee setup.log

- name: Install ruby
  connection: local
  hosts: workstation
#  remote_user: root
#  accelerate: true

  roles:
    - elao.sass

  vars:
        elao_ruby_deb_url: "deb http://deb.bearstech.com/debian jessie-bearstech main"
