---

- name: Apply security configuration
  hosts: jenkins-slaves
  become: true

  roles:
    - geerlingguy.security

  vars:
      security_ssh_password_authentication: "yes"
      security_ssh_permit_root_login: "yes"
      security_ssh_x11_forwarding: "yes"
      security_fail2ban_enabled: false
      security_autoupdate_enabled: false # make yum to get stuck later
