#sudo ansible-playbook -i hosts-albandri -c local -v sonar.yml -vvvv | tee setup.log

- hosts: all
  gather_facts: true
  tasks:
    - name: group hosts by distribution
      group_by: key="{{ ansible_distribution }}-{{ ansible_distribution_version }}"

- hosts: RedHat-7*:RedHat-6*:RedHat-5*:CentOS-7*:CentOS-6*:Ubuntu-18*:Ubuntu-17*:Ubuntu-16*:Ubuntu-14*:Ubuntu-13*:Ubuntu-12*
  gather_facts: false
  tasks:
    - name: group hosts for supported distributions
      group_by: key="supported"

- hosts: "!supported"
  gather_facts: false
  tasks:
    - name: fail for unsupported distribution
      fail: msg="{{ ansible_distribution }} {{ ansible_distribution_version }}
                 is not a supported OS for a Tower installation.  Supported
                 OSes include Red Hat Enterprise Linux 6/7, CentOS 6/7, or
                 Ubuntu 12.04/13.04/14.04/16.04/17.04/18.04."
    - debug: msg="Version {{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_architecture }}"

- name: Install sonar
  hosts: sonar
  #become: yes
  #remote_user: vagrant
  #connection: local

  roles:
    - role: sonar

  vars:
#TODO merge sonar-runner.properties.j2 file from jenkins_slave role
      sonar_analyzer_runner_install: false
#Handle by jenkins_slave role, Warning it will override settings.xml.j2 from jenkins_slave role
      maven_install: false
      sonar_mysql_install: true
      sonar_postgres_install : false
      sonar_jdbc_driver: "mysql"
      sonar_jdbc_port: 3306
      mysql_root_username: root
      mysql_root_password: microsoft
      sonar_jdbc_pass: "{{ mysql_root_password }}"
      sonar_login_user: "{{ mysql_root_username }}"
      sonar_login_password: "{{ mysql_root_password }}"
      sonar_shell: "/bin/false"
      sonar_name: "sonarqube-{{sonar_version}}"
      sonar_archive: "sonarqube-{{sonar_version}}.zip"
      sonar_major: "6"
      sonar_minor: "7.4"
      sonar_projects: []
      sonar_plugins :
          - name  : "Python support"
            url   : "http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/python/sonar-python-plugin/1.3/sonar-python-plugin-1.3.jar"

          - name  : "Java support"
            url   : "http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/java/sonar-java-plugin/2.9.1/sonar-java-plugin-2.9.1.jar"

          - name  : "JavaScript support"
            url   : "http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/javascript/sonar-javascript-plugin/2.2/sonar-javascript-plugin-2.2.jar"

          - name  : "Cxx support"
            url   : "http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/sonar-cxx-plugin/0.2/sonar-cxx-plugin-0.2.jar"

#          - name  : "Flex support"
#            url   : "http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/sonar-flex-plugin/2.1/sonar-flex-plugin-2.1.jar"

          - name  : "Groovy support"
            url   : "http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/sonar-groovy-plugin/1.0.1/sonar-groovy-plugin-1.0.1.jar"

          - name  : "Web HTML (included in HTML, JSP, JSF, Ruby, PHP, etc. pages) support"
            url   : "http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/sonar-web-plugin/2.3/sonar-web-plugin-2.3.jar"

          - name  : "XML support"
            url   : "http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/xml/sonar-xml-plugin/1.2/sonar-xml-plugin-1.2.jar"

#WARNING use 06-SNAPSHOT from git clone https://github.com/gvsmirnov/sonar-pitest.git
          - name  : "Pitest support"
            url   : "http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/sonar-pitest-plugin/0.5/sonar-pitest-plugin-0.5.jar"

          - name  : "Checkstyle support"
            url   : "http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/java/sonar-checkstyle-plugin/2.2/sonar-checkstyle-plugin-2.2.jar"

#          - name  : "Findbugs support"
#            url   : "http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/java/sonar-findbugs-plugin/3.1/sonar-findbugs-plugin-3.1.jar"

          - name  : "PMD support"
            url   : "http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/java/sonar-pmd-plugin/2.3/sonar-pmd-plugin-2.3.jar"

          - name  : "Generic Coverage support"
            url   : "http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/sonar-generic-coverage-plugin/1.1/sonar-generic-coverage-plugin-1.1.jar"

          - name  : "Clirr support"
            url   : "http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/sonar-clirr-plugin/1.2/sonar-clirr-plugin-1.2.jar"

#          - name  : "NCSS support"
#            url   : "http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/sonarncss/0.1/sonarncss-0.1.jar"

          - name  : "Artifact size support"
            url   : "http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/sonar-artifact-size-plugin/0.3/sonar-artifact-size-plugin-0.3.jar"

          - name  : "Build stability support"
            url   : "http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/sonar-build-stability-plugin/1.2.1/sonar-build-stability-plugin-1.2.1.jar"

          - name  : "Clover support"
            url   : "http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/sonar-clover-plugin/3.0/sonar-clover-plugin-3.0.jar"

          - name  : "CSS stability support"
            url   : "http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/css/sonar-css-plugin/1.1/sonar-css-plugin-1.1.jar"

          - name  : "Jmeter stability support"
            url   : "http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/jmeter/sonar-jmeter-plugin/0.2/sonar-jmeter-plugin-0.2.jar"

          - name  : "Cobertura support"
            url   : "http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/sonar-cobertura-plugin/1.6.3/sonar-cobertura-plugin-1.6.3.jar"

          - name  : "Crowd support"
            url   : "http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/sonar-crowd-plugin/2.0/sonar-crowd-plugin-2.0.jar"

          - name  : "JIRA support"
            url   : "http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/sonar-jira-plugin/1.2/sonar-jira-plugin-1.2.jar"

          - name  : "SCM activity support"
            url   : "http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/scm-activity/sonar-scm-activity-plugin/1.8/sonar-scm-activity-plugin-1.8.jar"

          - name  : "SCM stats support"
            url   : "http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/sonar-scm-stats-plugin/0.3.1/sonar-scm-stats-plugin-0.3.1.jar"
