---

# This playbook can be run using vagrant (on virtual box).
- name: configure supervisor
  hosts: supervisors
  become: true

  roles:
    - role: supervisor
      name: webserver
      command: python -m SimpleHTTPServer
      directory: /opt/web
# user is the same as base_admin_username
      user: jenkins
