---
# To prevent OOM errors on docker hosts (can be included with docker playbook)

- name: configure swap
  hosts: jenkins-slaves
  become: true

  roles:
    - role: ansible-swapfile
      swapfile_size: 16GiB
      swapfile_swappiness: 20
      swapfile_location: /data/swap
