#ansible-playbook -i hosts-albandri -c local -v synergy.yml --ask-sudo | tee setup.log

# This playbook can be run using vagrant (on virtual box).
- name: Install synergy
  hosts: workstation
  #remote_user: root
  connection: local

  roles:
    - role: albanandrieu.synergy

  vars:
    #synergy_server_main: "10.25.40.139"
    synergy_server_desktop: "albandrieu"
    synergy_server_laptop: "albandrieu-dell-5420"
    synergy_major: "1"
    synergy_minor: "14.3.stable"
    synergy_number: "218fa800"
    #synergy_url: "http://albandrieu.com:84/nabla/html/download/synergy/{{synergy_package_deb}}"
    synergy_url: "http://192.168.132.24:8680/download/synergy/{{synergy_package_deb}}"
