#sudo ansible-playbook -i hosts-albandri -c local -v tomcat.yml | tee setup.log

- name: Install tomcat
  hosts: workstation
  remote_user: albandri
#  connection: local

  roles:
    - alban.andrieu.tomcat

  vars:
       tomcat_started_check_enable: yes
       tomcat_version: "8"
       tomcat_keystore_file: "/workspace/users/albandri10/.keystore"
#      user: root
#      home: "/root"
