---
# ansible-playbook varnish.yml -i production --limit albandri.nabla.mobi -vvvv

- name: Install varnish
  hosts: varnish
  become: yes
#  ignore_errors: true

  roles:
      - role: geerlingguy.varnish
        varnish_admin_listen_host: "127.0.0.1"
        varnish_admin_listen_port: "6082"
        varnish_listen_port: "80"
        varnish_default_backend_host: "127.0.0.1"
        varnish_default_backend_port: "8080"
        varnish_backends:
          - backend: apache1
            host: "192.168.0.1"
            port: 80
          - backend: apache2
            host: "192.168.0.2"
            port: 80
        varnish_vhosts:
          - servername: web1.nabla.mobi
            backend: apache1
          - servername: web2.nabla.mobi
            backend: apache2
