#ansible-playbook -i playbooks/hosts-albandri-test -v playbooks/virtualbox.yml --limit albandri-test -vvvv

- name: Install virtualbox
  hosts: virtualbox
  become: true
  ignore_errors: true

  roles:
    - alban.andrieu.virtualbox

  vars:
    virtualbox_version: "5.2.26"
    virtualbox_package_name: virtualbox
    virtualbox_users:
      - "jenkins"
      - "micloud"
