---

# ansible-playbook -i playbooks/hosts-albandri-test -v playbooks/virtualbox.yml --limit albandri-test -vvvv

- name: Install virtualbox
  hosts: virtualbox
  become: true
  ignore_errors: true

  roles:
    - albanandrieu.virtualbox

  vars:
    #virtualbox_version: "5.2.26"
    virtualbox_version: "6.0.14-dfsg-1"
    virtualbox_package_name: virtualbox
    virtualbox_users:
      - "jenkins"
      - "micloud"
