#sudo ansible-playbook -i hosts-albandri -c local -v web.yml | tee setup.log
#TODO ansible -i hosts-albandri albandri --sudo --ask-sudo-pass -m raw -a "apt-get -f install && apt-get update"
#TODO ansible -i hosts-albandri albandri --sudo --ask-sudo-pass -m raw -a "apt-get install -y python3 python-simplejson"

#WARNING jenkins-master role has disabled a2dissite 000-default
- name: Configure and deploy the nabla php sample application code to apache
#  connection: local
  hosts: workstation
  remote_user: albandri
#  remote_user: root
  become: yes

  roles:
    - { role: alban.andrieu.web,
       apache_listen_port: 7075,
       web_base_dir: "/var/www/sample",
       #jenkins_proxy_port: "{{ apache_listen_port }}" #TODO why is it needed!!!
       phpmyadmin_mysql_user: root,
       phpmyadmin_mysql_password: microsoft,
       phpmyadmin_mysql_port: "{{ apache_listen_port }}",
       php_date_timezone: "Europe/Paris",
       mysql_innodb_log_file_size: "5M",
       mysql_root_username: root,
       mysql_root_password: microsoft,
       php_enable: no,
       repository: "https://github.com/AlbanAndrieu/nabla-servers-bower-sample.git",
       repository_version: "gh-pages",
       docker_files_enable: no,
       docker_files_generated_directory: "../roles/alban.andrieu.web",
       }
