---
#This script is used to configure your workstation (for developer)

#ansible windows -i hosts-albandri -m win_ping -vvvvv
#sudo ansible-playbook -i hosts-albandri -v windows.yml | tee setup.log

- name: Install Windows
  hosts: windows
  user: root

  roles:
    - role: albanandrieu.windows
