#ansible-playbook -i hosts-albandri -v workstation.yml --limit albandri --ask-sudo-pass -vvvv

- hosts: workstation
  gather_facts: true
  tasks:
    - name: group hosts by distribution
      group_by: key="{{ ansible_distribution }}-{{ ansible_distribution_version }}"

- hosts: Ubuntu-12.04:Ubuntu-14.04:Ubuntu-16.04
  gather_facts: false
  tasks:
    - name: group hosts for supported distributions
      group_by: key="supported"

- hosts: "!supported"
  gather_facts: false
  tasks:
    - name: fail for unsupported distribution
      fail: msg="{{ ansible_distribution }} {{ ansible_distribution_version }}
                 is not a supported OS for a Tower installation.  Supported
                 OSes include Ubuntu 12.04/14.04."

- name: Install worksation add-on
  hosts: workstation
#  remote_user: root
  remote_user: albandri
#  connection: local
#  become: yes

  roles:
    - alban.andrieu.workstation

  vars:
       dropbox_user_directory: "/workspace/Dropbox"
       dropbox_user_host: "2366450895"
       web_base_dir: "/var/www/sample"
       nodejs_enabled: false
       variety_owner: "{{ user }}"
       variety_group: "{{ group }}"
       dropbox_owner: "{{ user }}"
       dropbox_group: "{{ group }}"
