---
#ansible-playbook -i inventory/production -c local -v playbooks/yarn.yml --limit albandri.nabla.mobi --ask-sudo-pass | tee setup.log

- name: Install yarn
  hosts: jenkins-slaves
  become: yes
  ignore_errors: yes

  roles:
    - yarn
