---

- name: Debug
  hosts: zabbix-agent-paris-linux
  become: true

  pre_tasks:
  #- name: 'Include some additional variables'
  #  #include_vars: group_vars/all/vault.yml
  #  include_vars:
  #    dir: "group_vars/all"
  #    no_log: true

  - name: Show vault pass
    no_log: true
    debug:
      msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }} - {{ zabbix_api_pass }}"

#  - name: Show all variables
#    debug:
#      var: hostvars[inventory_hostname]
#      verbosity: 4

- name: Install zabbix-agent
  hosts: zabbix-agent-paris-linux
  become: true

  tasks:
    - include_role:
        name: zabbix

      vars:
        zabbix_version: 3.5
        zabbix_agent_server: albandrieu.com
        zabbix_agent_serveractive: albandrieu.com
        zabbix_agent_ip: 192.168.1.57
        zabbix_visible_hostname: "{{ zabbix_visible_name | default(ansible_fqdn) }}"
        zabbix_inventory_mode: automatic
        zabbix_url: https://albandrieu.com/zabbix/
        zabbix_api_use: true # use zabbix_api_create_hosts and/or zabbix_api_create_hostgroup from 0.8.0
        zabbix_useuip: 0 # 1 if connection to zabbix-agent is made via ip, 0 for fqdn.
        zabbix_create_host: present
        zabbix_api_create_hosts: true
        zabbix_agent_become_on_localhost: false
        #zabbix_api_create_hostgroup: true
        zabbix_api_user: "nabla"
        zabbix_api_pass: "microsoft"
        zabbix_host_groups:
          - NABLA Hosts
        zabbix_link_templates:
          - Template OS Linux
          - Template App SSH Service
        # zabbix_agent_include: /etc/zabbix/zabbix_agentd.d
        zabbix_agent_userparameters:
          - name: mysql
          - name: jenkins
            scripts_dir: jenkins
#        zabbix_agent_interfaces:
#          - type: 1
#            main: 1
#            useip: 0
#            dns: "{{ ansible_fqdn }}"
#          - type: 1
#            main: 0
#            useip: 1
#            ip: "{{ ansible_facts.default_ipv4.address }}"

- name: Install zabbix-agent
  hosts: zabbix-agent-gdynia
  become: true


  tasks:
    - include_role:
        name: zabbix

      vars:
        zabbix_version: 3.5
        zabbix_agent_server: albandrieu.com
        zabbix_agent_serveractive: albandrieu.com
        zabbix_agent_ip: 192.168.1.57
        zabbix_visible_hostname: "{{ zabbix_visible_name | default(ansible_fqdn) }}"
        zabbix_inventory_mode: automatic
        zabbix_url: https://albandrieu.com/zabbix/
        zabbix_api_use: true # use zabbix_api_create_hosts and/or zabbix_api_create_hostgroup from 0.8.0
        zabbix_create_host: present
        zabbix_api_create_hosts: true
        zabbix_agent_become_on_localhost: false
        #zabbix_api_create_hostgroup: true
        zabbix_api_user: "nabla"
        zabbix_api_pass: "microsoft"
        zabbix_host_groups:
          - NABLA Hosts
        zabbix_link_templates:
          - Template OS Linux
          - Template App SSH Service
